tediousjs/tedious

- src/connection.coffee
- test/integration/connection-test.coffee
Needed to make the following changes to support (in connection.coffee unless otherwise stated)
- New event needed for rerouting called as such "rerouting"
- Replaced previous "end" event on rerouting with aforementioned new event, "rerouting"
- Initialize tlsNegotiationComplete as false on start of SENT_TLSSSLNEGOTIATION
- Add server to serverName property in Login7Packet in the event the servername differs from the redirected hostname address (eg connect to serverA.net -> redirected to serverB.net -> server at serverB.net expects serverA's name for the server)
- Fixed up the integration/connection-test.coffee test to account for redirection on an encrypted server requiring 2 separate "encrypt" events, resulting in 3 additional successes in addition to the original expectation of 5 …
> Changes To Fix Rerouting on TLS Encrypted Connections  

- src/connection.coffee
- src/transaction.coffee
- test/integration/transactions-test.coffee
This adds a new transaction helper that makes the use of transactions a
breeze. It uses a mix of transactions and transaction savepoints to
enable correctly nested transactions, while giving the user the ability
to only roll back the contents of specific transaction blocks.
This is a potential breakage for existing users that make use of
`Connection#beginTransaction`, `Connection#rollbackTransaction` or
`Connection#commitTransaction`, but these never worked correctly in the
first place.
Fixes #152 
---
As described in #152, the use of nested transactions is super broken in tedious in it's current form.
This PR adds `Connection#saveTransaction` to create transaction savepoints and uses that to build a `Connection#transaction` helper that correctly employs transactions and savepoints to …
> Fix transaction support and add new Connection#transaction helper.

- src/connection.coffee
- test/integration/datatypes-in-results-test.coffee
- test/integration/errors-test.coffee
- test/integration/parameterised-statements-test.coffee
- test/integration/prepare-execute-statements-test.coffee
- test/integration/tvp-test.coffee
I've had a stab at a possible patch for #226 based on ashelley's fix, with some tests, since it's very relevant to my interests.
I wasn't sure about coding conventions - I don't usually add parentheses around function calls in coffeescript, especially when one of them is a callback, but not all the code seemed to agree on whether to do so or not.
Critique gratefully accepted!
> Add error.number property and some simple tests for its correctness.

- src/login7-payload.coffee
- test/unit/login7-payload-test.coffee
This should resolve both #207 and #214. After this fix, I was able to connect to a SQL Server on an AD machine using AD credentials from both OS X and Ubuntu machines that were not members of the AD domain. Planning on further integration testing, but wanted to  get the conversation started. (cc @bretcope, @rossipedia)
> Fix #207 - Resolve issues with Login7 Payload

- src/connection.coffee
This addresses the issue described in #243.
It uses the `tls.createSecureContext` function instead of `crypto.createCredentials`.
Note - I wasn't sure how deprecations should be handled. The `tls.createSecureContext` function wasn't added until Node v0.11.14:
* http://nodejs.org/docs/v0.11.13/api/tls.html#tls_tls_createsecurecontext_details
* http://nodejs.org/docs/v0.11.14/api/tls.html#tls_tls_createsecurecontext_details
My first pull request, so let me know if I missed anything.
> Fix deprecation warning for #243.

- src/connection.coffee
- src/data-type.coffee
- src/request.coffee
- test/unit/validations.coffee
I finally found some time to finish integrated type validation. It's a basic set of validators that should prevent users seeing errors like `index out of range` or similar. It also adds basic type coercion, so `1` and `"1"` are both valid values for data type `Int`.
```javascript
request = new Request('select @name', function(err) {
err instanceof RequestError
err.code === "EPARAM"
err.message === "Validation failed for parameter 'name'. Value must be between 0 and 255."
});
request.addParameter("name", TYPES.TinyInt, 999);
connection.execSql(request);
```
Type validation applies on `execSql`, `execute` and `callProcedure` methods.
Feature is based on #202 discussion.
I believe this can be merged without a problem, but I wanted to be absolutely sure I didn't forgot about anything so I …
> Integrated type checks

- .travis.yml
- package.json
The last released version of 0.8 was in July 2014, and the last released version of 0.6 was somewhere in 2012. I think we can safely drop support for those.
> Drop old node versions

- src/connection.coffee
- test/integration/connection-test.coffee
- test/integration/errors-test.coffee
I recently switched my application to use `tedious` for connecting to SQL Server 2012, which mostly went smoothly. I did however notice that some stored procedures produced errors when ran through a `tedious` connection, when they worked when run via ODBC or SQL Server Management Studio.
By playing with the Query Options in SSMS I was able to find that I could reproduce the problem by unticking `SET ANSI_NULL_DFLT_ON`. According to [MSDN](http://msdn.microsoft.com/en-us/library/ms187375.aspx) the OLE DB and ODBC drivers set this flag by default. Perhaps `tedious` should set it too?
At the same time, perhaps a way of customizing what `getInitialSql` returns would be useful, but I thought that wasn't really for me to decide. For the moment, I have duck-punched it like this: 
```coffeescript …
```
> Set ansi_null_dflt_on on by default

- src/connection.coffee
This fixes a tiny issue where the continuation that was passed to the `transaction` method
would be called with one more argument than expected. This argument was always `undefined`,
and this bug was only affecting the `arguments.length` value.
> Do not pass additional arguments to transaction continuation.

- src/data-type.coffee
- test/unit/data-type.coffee
In some cases the date written and read from database are not the same. This only happens if the connection is established with options.useUTC = false. My node and sql server run both in the CET/CEST timezone.
Example: 
Input date "2015-06-18T22:00:00Z" -> 2015-06-19 00:00:00 CEST
Output date "2015-06-17T22:00:00Z" -> 2015-06-18 00:00:00 CEST
This was caused because the EPOCH_DATE used to calculate the days since 1900-01-01 did not consider the daylight savings difference. The calculated difference was 42171.958333333336, which was floored down to 42171. When taking the DST into account the difference would be 42172 days.
fixed datatypes:
datetime
datetime2
smalldatetime
date
> fix daylight saving issue for non utc dates

- src/data-type.coffee
The current data-type.js validation for datetime, does not account for 'Invalid Date' validation. As a result, the driver throws an uncaught exception.
Example: new Date('16:24') will pass the validation function but when reaches writable-tracking-buffer.js, just blows up. Such request, if within a transaction, leaves the transaction unresolved till the app exits.
> data-type validation should validate 'Invalid Date'

- appveyor.yml
- scripts/appveyor/config.ps1
AppVeyor builds sometimes fail because requests fail to complete in the default request time of 15 seconds, so let's increase the timeout value a bit.
> Fix AppVeyor CI Flakiness

- .travis.yml
This extends the travis config to automatically publish a new `tedious` package after a git tag was pushed and the travis build for the tag passed.
---
This probably needs some discussion. //cc @bretcope @pekim @patriksimek 
The idea here is to use automation wherever possible, and to align the workflow between all collaborators. E.g. the 1.10.0 release was a bit messy, we (still) don't have a git tag for it, and the tests actually failed on travis, because the package.json contained the `^` symbol which does not work on Node < `0.10`.
> Publish npm modules through travis

- .travis.yml
- package.json
npmjs.com recently changed the API Key format, which caused the automatic release for 1.11.3 to fail (see #286).
Let's do another release that's identical with 1.11.3, hopefully working this time.
> Release 1.11.4

- src/connection.coffee
- src/message-io.coffee
Right now, the TLS handling code is spread over both the `Connection` as well as the `MessageIO` classes. This PR is meant to amend this and bring all TLS handling code together into the `MessageIO` class.
> Refactor TLS Handling

- .travis.yml
- appveyor.yml
This changes the CI configs for AppVeyor and Travis to run builds with the same Node.JS / iojs versions. It also adds caching for the `node_modules` folder, to speed up the builds.
On Travis, this reduces the total build time by ~30 seconds, while I'm not so sure whether caching has any impact on the AppVeyor build.
> CI config changes

- package.json
* #297 Fix #295 (Windows Domain Authentication no longer working). This issue was accidentally introduced by #285.
> Release 1.12.2

- src/connection.coffee
This fixes #262, #307 and #269. I also believe it fixes #258.
It's a bit simpler than the fix proposed in #269, and passes all unit and integration tests.
I can push a beta package to npm with this fix in place, if anyone is interested in testing this. I'll release `1.11.5` including this fix and I'll port the fix to 1.12 and the `master` branch once someone confirms this is working for them.
//cc @gleeds @bretcope @tysjiang @SyRenity @spanditcaa PTAL
> Don't overwrite configuration with routing data.

- .travis.yml
- appveyor.yml
Let's stop running CI builds on iojs and instead run them on the latest Node 4 release.
> Run Travis and AppVeyor builds with Node 4, instead of iojs.

- src/message-io.js
- src/metadata-parser.js
- src/token/colmetadata-token-parser.js
- src/token/done-token-parser.js
- src/token/env-change-token-parser.js
- src/token/infoerror-token-parser.js
- src/token/loginack-token-parser.js
- src/token/nbcrow-token-parser.js
- src/token/order-token-parser.js
- src/token/returnstatus-token-parser.js
- src/token/returnvalue-token-parser.js
- src/token/row-token-parser.js
- src/token/sspi-token-parser.js
- src/token/stream-parser.js
- src/token/token-stream-parser.js
- src/value-parser.js
The switch to a generator based parser in #285 brought better performance and decreased memory usage with large column values, but significantly decreased performance when processing a large number of result rows containing small column values. See #303 for more information.
---
This PR replaces all use of generator functions with a callback based approach. It is definately less elegant, but also has a much better performance profile.
Here's the benchmarks so far:
```
$ node benchmarks/
Many result rows x 7.19 ops/sec ±1.40% (38 runs sampled)
Memory: 25.03125 MiB
inserting nvarchar(max) with 5242880 chars x 15.00 ops/sec ±1.60% (69 runs sampled)
Memory: 28.88671875 MiB
inserting nvarchar(max) with 4 chars x 70.06 ops/sec ±0.38% (29 runs sampled)
Memory: 7.65234375 MiB
inserting …
```
> Remove use of generator functions

- src/data-type.js
- test/integration/binary-insert-test.coffee
Binary data is truncated on insert. Only the first byte of the buffer is written, the following ones are set to 0.
This is a regression from 1.8.0. I fixed it by restoring the `declaration()` function from 1.8.0.
I've added a unit test. It should probably be merged into one of the existing unit tests but I did not know how to best do it.
> Binary data truncated on insert

- src/rpcrequest-payload.js
- test/integration/parameterised-statements-test.coffee
This fixes #335.
I accidentally introduced a typo when converting this part of the code from CoffeeScript to Javascript. Unfortunately, there were no test cases for the `DateTime2` parameter type, so the issue was not found through our automated test cases.
This fixes the typo and adds test cases to ensure we don't introduce a similar issue again.
//cc @pawelrychlik @sentient Can you take a look? If this looks good to you, I'll push a new release with this fix included.
> Fix issues with DateTime2 parameters

- src/value-parser.js
When reading nvarchar max, ensure data is not falsey fixes nvarchar(max) columns on sql 2005
see https://github.com/pekim/tedious/issues/327
not sure why this doesn't fail on sql 2008+? Somehow data is never null even if db value is null?
> Fix for nvarchar(max) columns on sql 2005

- package.json
- src/value-parser.js
Another small bugfix release for an issue introduced in 1.13.0.
#340 Fix handling of null values in `nvarchar(max)` columns.
> Release 1.13.2

- _config.yml
- changelog.html
- index.html
The changelog was pretty out of date so I took a quick stab at updating it.
I also removed the index notice about the source of Tedious being in CoffeeScript as it has since been converted to ES2016.
Lastly to fix a Github Pages build/Jekyll error I converted from trying to use pygments (unsupported on Github Pages) to rouge.
> Update documentation changelog and remove CoffeeScript notice

- README.md
The README had links that now 404.  Updated them to the new URLs.  
Also updated the build badge for dependency status (david-dm) as it could not find the project under pekim anymore.
AppVeyor/Travis on the other hand only find it under pekim and not tediousjs so I left that one pointing to the old one...
> Updated README to point to the new organization URLs as required.

- api-request.html
In my testing, I had to wait for the `prepared` event before `Connection.execute` would work properly. I discovered this undocumented event by looking at the test cases.
> Document Request event 'prepared'

- src/connection.js
- src/message-io.js
This allows accepting or rejecting a connection to a server that presents an untrusted certificate.
This fixes #397 and #399.
---
@SimonHooker Sorry this has taken me so long. 😞 I took your commits, squashed them together, and fixed a few issues (both style wise as well as a "this won't actually do the right thing in case of an certification verification error"). Please take a final look, and if everything looks good, I'll merge this ASAP.
> Add `options.trustServerCertificate`.

- src/guid-parser.js
This is based on an idea suggested by @jdanyow. Instead of converting individual bytes of the GUID to strings using `Number#toString` and uppercasing them later, we use a predefined map that allows us to lookup the uppercased hex representation of the individual bytes extremely fast. This easily improves the performance of the GUID string generation by 2500 times.
This fixes #429.
> Improve performance of queries that select GUID columns.

- src/connection.js
- test/integration/connection-test.coffee
This addresses the issue:
https://github.com/tediousjs/tedious/issues/414
The issues speaks to FDQN in addition to the pull request. But I couldn't repro the FDQN failure. It seems to work for me just fine.
@arthurschreiber @arobson  - This is a follow-up to our discussion on https://github.com/tediousjs/tedious/issues/246.
> NTLM authentication requires domain to be upper case 

- src/value-parser.js
- test/integration/parameterised-statements-test.coffee
@arthurschreiber This should move https://github.com/tediousjs/tedious/pull/420 forward. This PR fixes several of the test failures against older versions of TDS. Please merge the changes if they look good.
This does not fix all the failures. There are still 4 tests failing in transactions-test.coffee against 7.1 only. Not sure yet if these tests can be made 7.2 and above only or if these are bugs.
> Tds multi version

- src/connection.js
- test/integration/transactions-test.coffee
events 'beginTransaction', 'commitTransaction' and 'rollbackTransaction'.
These are all available only for TDS versions 7.2 and over. This is
causing several transaction integration tests to fail.
This PR attempts to fill in the gaps by managing inTransaction state based
on equivalent events and callbacks for TDS versions below 7.2. All the
tests pass now except for
transactionHelperMixedWithLowLevelTransactionMethods.
> Currently inTransaction state on Connection is maintained based on the

- src/connection.js
This will impact on all query if database name is not specified in their
query.
> Incorrect conditional statement

- src/connection.js
- src/message-io.js
Setting `trustServerCertificate`to `false` makes `tedious` check the server's certificate for validity, but it does not actually check that the hostname we tried connecting to is also listed in the certificate. This means the server side could present **any** valid certificate and `tedious` would happily connect to it. That's bad. 😞 
/cc @SimonHooker If you got some time, please take a look!
/cc @tvrprasad I want this to go into 1.15.0 as well.
> Verify the server's hostname against the certificate.

- src/tedious.js
Unless I'm missing something, it seems that you can't easily instantiate a ConnectionError or RequestError with the current exports from tedious.js. I find that this makes it difficult to interrogate errors returned from the library, i.e. by using instanceof, such as in the following code:
```
tds.process(function(err, data) {
if (err) {
if (err instanceof ConnectionError) {
manageConnectionError(err);
} else if (err instanceof RequestError) {
manageRequestError(err);
}
}
else {
doStuff(data);
} 
});
```
It seems like exporting the error types would make it easier to write code like the above.
I'm relatively new to working with JavaScript, so it may be that there's a reason this isn't being done, or that this isn't actually necessary.  My apologies if that's the case.
> Add ConnectionError and RequestError to module.exports

- src/data-type.js
- test/integration/parameterised-statements-test.coffee
- test/unit/validations.coffee
This addresses https://github.com/tediousjs/tedious/issues/490 opened by @beautifulcoder
@arthurschreiber This fixes what amounts to data corruption on insertions, which makes it important to fix soon. But this is also a breaking change in terms of behavior. Any thoughts on if should we wait for 2.0 to check this in or get this into the up coming 1.x release?
> Added range validation for BigInt data type.

- src/connection.js
- test/integration/connection-test.coffee
I need the behavior afforded by the SET ARITHABORT ON setting, in order to use this driver, as part of patriksimek's node-mssql driver. I have been modifying this setting manually in the lib/connection.js file for a few versions now, every time I upgrade the node_modules for my product.
My changes leave the ARITHABORT default "off", as you currently have it, but I should also point out the recommendation from the RDBMS developer's [SET ARITHABORT (Transact-SQL) manual page](https://msdn.microsoft.com/en-us/library/ms190306.aspx), on the "Remarks" paragraph, states: "You should always set ARITHABORT to ON in your logon sessions. Setting ARITHABORT to OFF can negatively impact query optimization leading to performance issues."
> Make SET ARITHABORT configurable

- src/data-type.js
- src/value-parser.js
Fix #391 #428
When insert millisecond value into datatime column by SQL literal,
values are rounded as follows.
.990->990(297 * 1/300 second)
.991->990
.992->993(298 * 1/300 second)
.993->993
.994->993
.995->997(299 * 1/300 second)
.996->997
.997->997
.998->997
.999->000(300 * 1/300 second)
current code omit  the figures twice(set & get time) as follows
.990->990(297 * 1/300 second)
.991->990
.992->990
.993->990
.994->993(298 * 1/300 second)
.995->993
.996->993
.997->996(299 * 1/300 second)
.998->996
.999->996
> Round DateTime millisecond to 0,3,7

- src/connection.js
This creeped in PR https://github.com/tediousjs/tedious/pull/503.
Curiously enough the unit tests added as part of the CL caught the bug
when I ran tests on my machine whereas they succeeded on AppVeyor. The
difference is that I happened to have a 'port' config value set in my
local setup whereas AppVeyor did not. Just a freak coincidence that this
would trigger the bug.
> Fixed a bug in datefirst validation.

- src/connection.js
Without calling clearRequestTimer() in Connection.cancel(), the old timer remains active when a request is canceled. Even after a new request is started and createRequestTimer() is called again, the old timer still remains active.
> add missing this.clearRequestTimer() to Connection.cancel()

- src/tracking-buffer/writable-tracking-buffer.js
In the current implementation of WritableTrackingBuffer, a new internal buffer of initialSize bytes is allocated each time the data property of the WritableTrackingBuffer is accessed. This is because the getter method of WritableTrackingBuffer.data calls newBuffer(0) and newBuffer() sets the size parameter to initialSize if it is zero.
> Avoid unnecessary allocation in WritableTrackingBuffer

- src/connection.js
This behavior is according to the TDS standard.
> Stop request timer when first packet of response message is received

- src/connection.js
- src/instance-lookup.js
- src/sender.js
- test/integration/instance-lookup-test.coffee
- test/unit/instance-lookup-test.js
- test/unit/sender-test.js
comprehensive unit testing.
- Refactored UDP code to send message to SQL server browser into a
separate class 'Sender' class. Somewhat similar to Connector class.
- Added comprehensive unit tests, stubbing with Sinon.
- Wrapped code in instance-lookup.js in class to make the code more unit
testable.
- Currently unit tests for instance-lookup are pretty light. Added more
comprehensive tests.
- This is a squash of several commits from the branch:
- https://github.com/tvrprasad/tedious/tree/multisubnet-failover-udpv6
> Extensive refactoring of instance-lookup code to support UDP v6 and

- test/unit/sender-test.js
Replaced with EventEmitter.listeners.
@arthurschreiber This'll fix the test failures in https://github.com/tediousjs/tedious/pull/362 for Node 0.10 and 0.12. Please merge.
> EventEmitter.listenerCount is not supported in 0.10 and 0.12.

- src/connection.js
Node 7.7.2 introduced a bug in socket.connect, where you get an error:
typeerror: "listener" argument must be a function
Switched to net.connect which does not have this bug.
CI tests are failing for https://github.com/tediousjs/tedious/pull/518 due to this bug.
> Work-around socket.connect bug in Node 7.7.2

- .travis.yml
This removes the auto-release configuration I had put in place a while ago. I plan to re-introduce this using `semantic-release` in the future, but let's just remove this for now.
> chore: Remove auto-release configuration.

- .travis.yml
- appveyor.yml
- package.json
As discussed in https://github.com/tediousjs/tedious/issues/495, this removes support for unsupported Node.js versions and removes them from our CI builds. It also updates our `package.json` to highlight the fact we support Node.js 4+ only.
Fixes https://github.com/tediousjs/tedious/issues/495 and https://github.com/tediousjs/tedious/pull/496.
> Drop support for unsupported Node.js versions

- src/connection.js
Since 8b70dbdb37e73eba80c3c39719ce96fee9dedac7 the debug options had no longer an effect.
> Fix debug options

- package.json
- test/setup.js
When we initially migrated back to ES6+, I added a check here to make sure that no future JavaScript syntax was being used that was not also supported by the current Node LTS (4.x at the time).
After having this around for some while, I no longer believe this is worth the trouble. We should just support all the syntax that was standardized and is supported by transpilation via babel. This should also be less confusing to people who contribute code to `tedious`.
/cc @tvrprasad
> Always transpile all code when running unit tests

- package.json
- src/connector.js
- src/sender.js
We used `dns-lookup-all` to support older Node.js versions that lacked support for the `all` option of `dns.lookup`. Now that we dropped support for older Node.js versions, we can also stop using `dns-lookup-all`.
> Drop dependency on `dns-lookup-all`

- package.json
`babel-preset-env` is a relatively new babel preset that can automatically determine which language features need to be transpiled based on the targets environments that are specified in the configuration. In our case, the target is currently Node.JS 4 (until that version goes out of support).
> Switch to `babel-preset-env`

- package.json
- test/setup.js
While looking through the travis errors of #566 at https://travis-ci.org/tediousjs/tedious/jobs/220815074, I noticed that the stack traces for Coffee Script code are all messed up.
After some fiddling around, I figured out that this is because both `coffee-script/register` as well as `babel-register` (via `source-map-support`) install a custom `Error.prepareStackTrace` function, and the former gets overwritten by the latter.
Fortunately, `coffee-script/register` generates inline source maps in the transpilation result, and `source-map-support` has optional support for these source maps, but it's not enabled in `babel-register`. But enabling it is easy, so we can make sure stack traces look good for code transpiled through `coffee-script` as well as `babel`. 👍
> Fix coffee script stack traces in tests

- .travis.yml
- package.json
Now that we run the full integration test suite across all supported Node.JS versions on travis (#564), we can use `semantic-release` to automatically publish new versions of `tedious` after each merge to `master`.
> Automatic releases via `semantic-release`

- .travis.yml
- appveyor.yml
Node 8 was released, so we probably should start running our CI builds against it.
> chore: Run travis builds against Node 8.

- src/connection.js
- test/integration/connection-test.js
dateFormat, enableAnsiNull, enableAnsiPadding, enableAnsiWarnings,
enableConcatNullYeldsNull, enableCursorCloseOnCommit,
enableImplicitTransactions, enableNumericRoundabort, enableQuotedIdentifier,
language.
Relates to #507 #506 #501 #503
This is a cleaned up merged version of #508.
> Add additional config options:

- src/connection.js
- src/message-io.js
- src/request.js
- src/token/stream-parser.js
- src/token/token-stream-parser.js
- test/integration/pause-resume-test.js
This pull request adds the two methods Request.pause() and Request.resume() to the public Tedious API. They can be used to pause and resume the flow of data rows from a query result. A test case is included.
See #181 for the reasons why this extension is important.
> Implements Request.pause() / resume()

- src/login7-payload.js
- test/unit/login7-payload-test.js
This fixes a potentially security relevant issue where `tedious` would send username and password in plaintext via the LOGIN7 token, even if the `domain` option was specified and the credentials were sent as hashes via NTLM.
The security impact of this is rather low, as NTLM hashes are not really much more secure than plain text credentials, but this is still something we should fix.
> fix: Do not send username and password via LOGIN7 when a domain is set.

- package.json
- src/connection.js
- src/token/sspi-token-parser.js
- test/integration/connection-test.js
- test/unit/token/sspi-token-parser-test.js
The `sspi-client` that was added to support native windows
authentication requires a small amount of C++ code to be compiled via
`node-gyp` during installation. This is not support on Azure out-of-the
box.
As the native windows authentication was never documented and only
accidentally included in the 2.1.0 release, we can remove the code to
support it to fix deployments for Azure users.
Native windows authentication will be brought back and supported in
future `tedious` releases.
> Fix: Fix deployments to Azure.

- .travis.yml
- appveyor.yml
- package.json
Instead of running `eslint` before `test`, `test-integration` and
`test-all` scripts, we only run it before `test`.
> chore: Only run `eslint` once.

- .travis.yml
This switches us to run `npm run semantic-release` in a separate build stage on Travis CI.
More information about build stages can be found here: https://docs.travis-ci.com/user/build-stages/
> chore: Run `semantic-release` in separate build stage.

- src/value-parser.js
As documented in bug #625, setters are a bit on the unpredictable side, `setDate` can, under certain circumstances, change the time of the `Date` object, preventing other calls from working correctly.
Missing unit tests of which I'm unsure of how to approach.
> Use Date constructors over unpredictable setters (fixes #625)

- package.json
- test/setup.js
This was required to get correct stack-traces back when tedious was still written in CoffeeScript, but is not required anymore.
> chore: Drop the use and dependency on `source-map-support`.

- src/connection.js
> Connection to Azure SQL Data Warehouse fails with ERROR: 'CursorCloseOnCommit' is not a recognized option.
Cursor_close_on_commit is not supported by DW, since this is OFF by default, if user doesn't set it in config, avoid sending it in initial SQL.
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-cursor-close-on-commit-transact-sql
Fixes #631
> fix: connection failure in Azure SQL Data Warehouse

- .travis.yml
- appveyor.yml
This updates the Node.js versions that we use to run our tests on during CI on Travis and Appveyor. Node.js 7.x is no longer maintained or supported, 8.x became the new long-term support release, and new development happens on 9.x now.
> chore: Upgrade Node.js versions used for CI.

- .travis.yml
- appveyor.yml
Instead of running the linter on each CI build on Appveyor and Travis,
we now run it once in a separate build step on Travis. This should stop
us from spending time performing the same checks multiple times.
> chore: Only run the linter once during CI.

- appveyor.yml
I noticed that some builds on Appveyor started to get really slow. I figured that one of the reasons for this was that we never remove no-longer used modules from the module cache on Appveyor. 😓
> chore: Prune unused node modules from the Appveyor build cache.

- package.json
* `babel-cli@6.26.0`
* `babel-eslint@7.2.3`
* `babel-register@6.26.0`
* `babel-runtime@6.26.0`
* `babel-preset-env@1.6.1`
This is mostly to get `babel` parsing support for some of the newer `flow` features, before we introduce `flow` typing to the tedious source.
> chore: Upgrade `babel` related packages.

- src/connection.js
This is a follow up to #643 and fine-tunes the way the `enableCursorCloseOnCommit` connection option is handled.
Instead of only sending the `cursor_close_on_commit` option in the initial sql query payload if the `enableCursorCloseOnCommit` is explicitly set to `true` (without any option to disable `cursor_close_on_commit`), `tedious` now defaults to not sending `cursor_close_on_commit`. But if `enableCursorCloseOnCommit` is set to `true` or `false` explicitly, we either enable or disable this option in the initial sql query payload.
This way, users can decide whether they want to have the server's default `cursor_close_on_commit` value (by not specifying `enableCursorCloseOnCommit`), or explicitly set it to their required value.
> fix: Only set `cursor_close_on_commit` if explicitly specified.

- src/value-parser.js
readBinary would prevent image lengths of 65535 by doing a NULL check. This fix skips the NULL check and moves directly to readBuffer to retrieve the Image.
I am extracting 50k+ images from a database and a couple of the images had this issue and were throwing errors because the requested image data was assumed to be invalid and was not extracted and returned. This would then cause the stream parser (token/stream-parser.js) to throw errors on this line: 
`this.emit('error', new Error('Unknown type: ' + type));` 
because it did not know how to parse the remaining image data.
> Allow length of 65535 for images. 

- src/ntlm-payload.js
- src/packet.js
- src/prelogin-payload.js
- src/tracking-buffer/bigint.js
- src/tracking-buffer/writable-tracking-buffer.js
- src/value-parser.js
Prior to Node.js 8.0.0, `Buffer` objects created via `new Buffer(size)` were not zero filled by default.
---
`new Buffer` has been deprecated since Node.js 6.0.0 in favor of `Buffer.alloc`, but as we still support 4.0.0, we can't switch to the new `Buffer.alloc` yet. 😞 
I don't think this fix is security relevant, as `WritableTrackingBuffer` always kept track of how many bytes were actually written to the buffer and never returned non-initialized data from the buffer. Still, zero filling the `Buffer` objects is good practice, so let's do that.
> fix: Ensure `Buffer`s are zero-filled on creation.

- src/request.js
'prepared' was emitted on error because the callback error argument was not checked.
'prepared' was emitted again if an error occurred again before the emit call returned
because the prepared flag was only updated after emitting the event.
> fix: avoid (repeatedly) emitting 'prepared' event on error

- src/bulk-load.js
- src/connection.js
- src/data-type.js
- src/instance-lookup.js
- src/message-io.js
- src/packet.js
- src/prelogin-payload.js
- src/request.js
- src/tracking-buffer/writable-tracking-buffer.js
While working on adding flow type information to the `tedious` source code, some CoffeeScript leftovers started to get in the way. 😞 
One of the leftovers from the conversion are stray `return` statements. In CoffeeScript, the last statement in a function was implicitly and automatically used as the return value of the function. This is really annoying when adding types to functions, as that means functions can have different result types depending on the execution path taken through the function. Even more annoying when we consider the fact that many of these functions were not supposed to have a return value in the first place (and the `return` statement generated by CoffeeScript returned useless information).
This gets rid of many of these return statements, cleaning up the code and …
> refactor: Reduce the number of explicit `return` statements.

- src/connection.js
issue #659 : socket is assigned and attempted to connect after the connection has transitioned to final state by connect timeout.
> Fix Issue #659

- package.json
I want to pull in `depd` to allow us to deprecate uses of `tedious` that will change in the future.
> chore: Add `depd@1.1.2`.

- src/data-type.js
- src/data-types/date.js
- src/data-types/datetime2.js
- src/data-types/datetimeoffset.js
- src/data-types/time.js
- src/data-types/uniqueidentifier.js
- src/value-parser.js
- test/integration/parameterised-statements-test.js
- test/unit/data-type.js
- test/unit/token/row-token-parser-test.js
This deprecates data type aliases  `DateN`, `DateTime2N`, `DateTimeOffsetN`, `TimeN` and `UniqueIdentifierN` in favor of their 'proper' names.
* `DateN` -> `Date`
* `DateTime2N` -> `DateTime2`
* `DateTimeOffsetN` -> `DateTimeOffset`
* `TimeN` -> `Time`
* `UniqueIdentifierN` -> `UniqueIdentifier`
The deprecated aliases will be removed in the next major version, together with types that shouldn't have been exposed in the first place (`IntN`, `BitN`, `DateTimeN`, etc.).
>  feature: Deprecate data type aliases.

- api-connection.html
Correcting the typo in port number used by SQL Server Browser Service to [1434 ](https://technet.microsoft.com/en-us/library/ms181087(v=sql.105).aspx#Anchor_0):smile:
> doc: Correct the UDP port number used by SQL Server Browser.

- package.json
I disabled `verifyConditions` some while ago to make `semantic-release` work with Travis build stages.
There's now build in support for Travis build stages. Also `plugin-noop` does not exist anymore and causes `semantic-release` to fail right now. 😞
> chore: re-enable default `verifyConditions` for `semantic-release`

- src/connection.js
Both of these values can't be used for ports and will cause failures further down when we try to actually establish a connection.
> fix: `options.port` should not be `0` or `65536`

- package.json
- src/connector.js
- src/sender.js
- test/unit/connector-test.js
- test/unit/instance-lookup-test.js
Use ASCII Compatible Encoding (ACE) value of domain name by default during connection.
I had to close #704 due to messed up commit name 😅 (not according to commitlint standard).
> feat: IDN support

- src/instance-lookup.js
- test/unit/instance-lookup-test.js
Using incorrect/non-existent instanceName in config throws an error that lists all the instance names (in that SQL Server), along with their port number and few other details. This PR alters the error to contain just the Server name.
Current message looks like:
> Port for <> not found in ServerName;Rx:<>;InstanceName;<instance1>;IsClustered;<>;Version;<>;tcp;<>;;ServerName;Rx:<>;InstanceName;<instance2>;IsClustered;<>;Version;<>;tcp;<>; ......
> fix: error should not expose all port numbers and instance names of SQL Server

- src/connection.js
- test/unit/connection-config-validation.js
- test/unit/tedious-test.js
This change ~deprecates the passing of non-`boolean` values for `options.encrypt`, and also~ deprecates relying on the current default value for `options.encrypt`.
This is in preparation for future breaking changes. See #694 for more information.
> feat: deprecations around `options.encrypt`

- src/connection.js
- src/message-io.js
- test/integration/connection-test.js
This fixes an issue in the TLS negotiation code of `tedious` that has been around for quite some time. 😞I also think this is one of the issues that has been plagueing people that wanted to use `tedious` in combination with encrypted connections (as is required e.g. when connecting to Azure).
Errors happening in the TLS layer were basically not handled at all. Usually, unhandled `error` events cause an uncaught exception in node.js (and bring down the whole process), but it looks like that this is not happening on `SecurePair`/`TLSSocket` instances. 🤷‍♂️ In our cases, these unhandled errors caused the connection to just go into some weird blocking state and become unusable. This most likely also caused issues with connection pool libraries. 🤔 
Anyway, by listening to `error` events and …
> fix: improve handling of TLS errors

- package.json
- test/.eslintrc
- test/integration/binary-insert-test.js
- test/mocha.opts
- test/setup.js
`nodeunit` is officially deprecated and unsupported, since a few days. See https://github.com/caolan/nodeunit#deprecated-project for more information.
This, and the fact that `nodeunit` has been causing me grief for a long time now with it's weird behaviour, brought me back to look into a replacement. This is a second attempt to move us to `mocha` and `chai`, but this time it's inspired by a comment made by @Hadis-Fard over in https://github.com/tediousjs/tedious/pull/150#issuecomment-357076448. As suggested there, this PR lays the foundation for a gradual migration from `nodeunit` to `mocha`.
I included one example conversion for reference.
> Prepare for a gradual move to `mocha`

- src/data-type.js
- test/unit/token/row-token-parser-test.js
Fixes #321 
>Since NULL is not a SQL Server data type, the sp_executesql query formed with null as type will run into syntax error (in Server side).
>
>plus, from TDS spec,
>
>    NULLTYPE can be sent to SQL Server (for example, in RPCRequest), but SQL Server never emits NULLTYPE data.
> feat: deprecate type null

- src/incoming-message-stream.js
- src/message-io.js
- src/message.js
- src/outgoing-message-stream.js
- test/integration/pause-resume-test.js
- test/unit/incoming-message-stream-test.js
- test/unit/message-test.js
- test/unit/outgoing-message-stream-test.js
For as long as `tedious` has existed, it's internals have been very unsupportive of stream based processing. The two main disadvantages of this are higher memory usage (because data is buffered) and lower performance (data is only sent after everything was buffered).
Previous changes in `tedious`'s internals moved us a bit closer to having internals be based on Node.js stream primitives, but we're still not there yet. 😅
This change here represents another big step in this direction. It introduces a new message based stream architecture and consists of three pieces:
* `Message`: A simple `PassThrough` stream that just forwards whatever is written into it, without modification.
* `IncomingMessageStream`: A `Transform` stream that takes in a raw TDS packet stream, creates `Message` instances …
> refactor: switch to a `Message` stream based architecture

- .travis.yml
> ci: run Travis lint stage on Node.js 6

- api-request.html
- bulk-load.html
Updating docs to use length as `Infinity` for max types. #725 & #679
+
documenting the `order` event in `Request`
> docs: improve documentation 

- src/connection.js
Further to https://github.com/tediousjs/tedious/pull/769 the change to correctly handle errors socket errors outside the final state.
The above PR failed to ensure that `socketError` events are allowed on the LOGGED_IN_SENDING_INITIAL_SQL state (a non-final state).
As such the following error can occur:
```
events.js:167
throw er; // Unhandled 'error' event
^
Error: No event 'socketError' in state 'LoggedInSendingInitialSql'
at Connection.dispatchEvent (./knex/node_modules/tedious/lib/connection.js:1014:28)
at Connection.socketError (./knex/node_modules/tedious/lib/connection.js:1030:12)
at Connection.socketEnd (./knex/node_modules/tedious/lib/connection.js:1047:14)
at Socket.<anonymous> (./knex/node_modules/tedious/lib/connection.js:884:18)
at Socket.emit (events.js:187:15)
at …
```
> FIX Allow socketError under state LOGGED_IN_SENDING_INITIAL_SQL

- src/connection.js
BREAKING CHANGE: This drops support for previousl deprecated 
configuration values and types, and makes the checks a lot stricter than 
before.
Many configuration options no longer accept `null` values and instead 
rely on values being present or `undefined` instead.
In other cases, configuration options that previously e.g. accepted 
string values and automatically converted them to numbers now only 
accept actual numbers.
Some options explicitly allow `null` values to be passed in and take 
that as a hint to use whatever is configured on the SQL Server instead.
---
Another change included here is a rework of how authentication options are specified. Instead of having to specify authentication options via the top level `userName`, `password` and `domain` options, a new `authentication` …
> Configuration rework

- src/connection.js
These two options should not treat `null` values like `undefined` either. This was deprecated before v4.x but the behaviour was not changed correctly when v4.0.0 was released.
> fix `null` handling for `trustServerCertificate` and `readOnlyIntent` config options

- src/message-io.js
SQLServer versions running on older Windows versions that have a buggy 
SSL/TLS implementation don't play well with the BEAST countermeasure 
implemented by OpenSSL, and cause the connection process to hang during 
the SSL/TLS handshake.
Due to the nature of the BEAST attack (it's specific to web browsers), 
we can safely disable the counter measures to fix the connection 
process, without jeopardizing security. 🎉
> Stop OpenSSL from inserting empty fragments

- .travis.yml
- appveyor.yml
- src/connection.js
- src/message-io.js
- test/integration/connection-test.js
- test/unit/tedious-test.js
This removes Node.js 9.x (no longer supported) and adds Node.js 11.x to the list of Node.js versions tested on Appveyor and Travis.
It also fixes compatibility with one of the breaking changes introduced in Node.js 11.x around `tls.createSecureContext` and the handling of invalid options.
> Fix compatibility on Node.js 11

- src/bulk-load.js
- src/connection.js
- src/message-io.js
- src/message.js
- src/outgoing-message-stream.js
- src/packet.js
- src/request.js
- test/integration/bulk-load-test.js
- test/integration/connection-test.js
- test/unit/bulk-load-test.js
- test/unit/request-test.js
This is an attempt to rework how request cancellation works, to make it more generic (it now works with regular requests and both streaming as well as non-streaming bulk loads) and more conformant to the MS-TDS spec.
This also adds a new `.cancel` method on the `Request` and `BulkLoad` classes, and deprecates the `cancel` method on the `Connection` class itself.
The changes in 8c9ce1d warrant a major version bump, as they change the behaviour of requests that are canceled after they were sent to the server. Instead of continuing to forward various events from the token stream parser to the canceled request, all this information will be "discarded", as described in [`3.2.5.8 Sent Attention State`](https://msdn.microsoft.com/en-us/library/dd340677.aspx) of the MS-TDS specification:
> If the …
> Rework request cancellation

- src/connection.js
- test/integration/connection-test.js
- test/integration/socket-error-test.js
When a socket error happens while a request is executed, the request's callback should be executed _after_ switching to the `FINAL` state.
This ensures we are consistent with the "happy path", where the connection is switched to the `LOGGED_IN` state before executing request callbacks. It'll also ensure that trying to send another request in the callback will fail with a `Requests can only be made in the LoggedIn state, not the Final state` message instead of `Requests can only be made in the LoggedIn state, not the SentClientRequest state`.
> fix: transition states before calling request callbacks

- appveyor.yml
- src/connection.js
This fixes an issue with NTLM authentication that was introduced with a recent refactoring, as reported in https://github.com/tediousjs/tedious/issues/856.
It also extends the AppVeyor configuration to enable NTLM authentication tests, so regressions will be caught much earlier in the future. 🙇 
This fixes https://github.com/tediousjs/tedious/issues/856
> Fix NTLM authentication

- .travis.yml
This adds a new stage on Travis CI called `tag-latest`, that will automatically tag the current version from the `next` release channel as `latest`, if that version was published at least 7 days ago.
This stage will be triggered daily via a Travis CI cron job.
> Automatically tag new releases as `latest` after a week

- src/bulk-load.js
- src/connection.js
- test/integration/bulk-load-test.js
This fixes a small issue with streaming `BulkLoad`s and request cancellation.
When a streaming bulk load request is cancelled, the row stream would still allow data to be written into it. By emitting a `error` event and destroying the stream, we can ensure that no more data can be written. This will also ensure that other streams that pipe into the row stream will be unpiped and can be cleaned up (e.g. by using `stream.pipeline`, this would happen automatically).
This could lead to request cancellation timeouts, as the row stream would keep continuing writing data to the message stream after the message ignore bit was set and the request cancellation timer could trigger before the row stream was ended.
> Cancellation: emit `error` on bulkload row streams

- src/incoming-message-stream.js
Fix for #877
@arthurschreiber could you have a look at this? In Tedious 2.7.0 you changed the data flow architecture to a stream of streams. The inner stream must also be paused.
> fix: flow control in message-io.js

- src/connection.js
- src/login7-payload.js
- test/unit/login7-payload-test.js
Fixes https://github.com/tediousjs/tedious/issues/745.
> Access token authentication

- .travis.yml
I'm not really sure what changed, but it looks like `npm` does not actually know anything about the `NPM_TOKEN` environment variable. This seems to have broken automatic releases recently, but I couldn't find any documentation that this should have worked, ever. 🤷‍♂️
> chore: fix npm configuration on Travis CI

- src/connection.js
Using Managed Service Identity (MSI) token forming connection will cause an error. It is caused by a logic flaw within the connection.js. This PR is fixing this specific error.
> fix: connection failure using Managed Service Identity (MSI) token due to the wrong authentication type

- src/incoming-message-stream.js
- test/unit/incoming-message-stream-test.js
The `IncomingMessageStream` handled the last packet of an incoming message incorrectly, when the stream was paused right before the that message was received. This could cause the `tedious` connection to become stuck in an undefined state and become unusable for further processing.
Fixes #899.
> Fix `IncomingMessageStream` packet processing when paused

- .travis.yml
Starting July 2019, npm caching on Travis is enabled by default, but unfortunately breaks the build on Node.js 6.x.
> Disable caching on Travis CI

- .travis.yml
`commitlint` seems to no longer support Node.js < 8.x, so let's just run the whole linting CI step on a version that is supported.
> Run linting CI step on Node.js 8.x

- .travis.yml
- appveyor.yml
- src/message-io.js
SQL Server expects individual TLS segments to never contain more data than the negotiated TDS packet size. If this is not the case, SQL Server will simply drop the connection without warning.
Since Node.js 12.4, `TLSSocket`s try to fit as much data as possible into a TLS fragment. Because the default TLS fragment size is `16384` bytes, and this does not necessarily match the negotiated TDS packet size, users of Node.js 12.4 and newer would encounter sudden connection drops (e.g. when sending large queries).
By keeping the TLS fragment size and the negoitated TDS packet size in sync, we can make sure SQL Server does not drop the connection.
Fixes: https://github.com/tediousjs/tedious/issues/923
> Fix compatibility with Node.js 12.4 and newer

- src/value-parser.js
This slightly cleans up the value parsing code's use of `readTextPointerNull` and `readDataLength`.
`readTextPointerNull` is now only called for `Image`, `Text` and `NText` data type.
`readDataLength` is now only called for variable length data types.
> Clean up some value parsing code

- src/connection.js
It adds Azure Active Directory *Service Principal Secret* Authorization method.
Usage:
```javascript
const connection = new Connection({
server: 'your-azure-database-server',
options: {
database: 'database_name',
encrypt: true
},
authentication: {
type: 'azure-active-directory-service-principal-secret',
options: {
clientId: '', // SERVICE PRINCIPAL CLIENT ID
clientSecret: '', // SERVICE PRINCIPAL CLIENT SECRET
tenantId: '', // SERVICE PRINCIPAL TENANT ID (domain)
}
}
});
```
> Add AAD Service Principal Secret authorization method

- src/data-types/datetime.ts
- test/integration/parameterised-statements-test.js
Datetime round millisecond in nearest .xx3, .xx7, .xx0, when the ms is rounded to 000 in case of 23:59:59:999, day should be incremented. the issue manifest itself in useUTC true or false
Fixes: #755
> fix: datetime max millisecond issue

- pull_request_template.md
- src/bulk-load.ts
Fixes #998 
This is a slightly different approach to fixing the problem than reinstating the `hasScale` flag (and other removed flags) from the `DataType` type; instead we infer the need to use `resolvePrecision` and `resolveScale` from the fact they are present.
This fixes a bug with `BulkLoad` where the error `Received an invalid column length from the bcp client for colid x` is thrown when scales are nor resolved for certain columns.
> FIX No longer rely on removed data-type props

- src/connection.ts
This moves the default for `config.options.encrypt` up into the base
configuration object, simplifying the setup and making it clearer
that the default is `encrypt: true` (and a minute bit faster).
Behaviour remains identical after this restructure.
----
1. [x] Ensure your fork is created from `master` branch of [the repository](https://github.com/tediousjs/tedious).
2. [x] Run `npm install` in the root folder.
3. [x] After bug fix/code change, ensure all the existing tests and new tests (if any) pass (`npm run-script test-all`). During development, to run individual test use `node_modules/nodeunit test/<test_file.js> -t <test_name>`.
4. [x] Build the driver (`npm run build`).
5. [x] Run eslint and flow typechecker (`npm run lint`).
6. [x] Run commitlint …
> refactor: simplify connection encrypt option

- api-connection.html
As of this commit (https://github.com/tediousjs/tedious/commit/70ffe4a) the default is to encrypt by default, so update the documentation accordingly
> docs: update options.encrypt default to true

- getting-started.html
This explains the encryption-by-default option whilst removing example that indicates that `{encrypt: true}` is necessary now.  See also #1000
> docs: update Getting Started example with options

- src/data-types/date.ts
- src/data-types/datetime.ts
- src/data-types/datetime2.ts
- src/data-types/datetimeoffset.ts
- src/data-types/smalldatetime.ts
- src/data-types/time.ts
- test/integration/parameterised-statements-test.js
This fixes the issue described in https://github.com/tediousjs/tedious/issues/339.
Fixes: https://github.com/tediousjs/tedious/issues/339
> fix: allow using `string` values for date related parameters

- src/data-types/bigint.ts
- src/data-types/int.ts
- src/data-types/smallint.ts
- src/data-types/tinyint.ts
- test/unit/int-data-type.js
Using `parseInt` in parsing string to numbers would have different result for the same value, using `Math.round` would fix the issue (#814)
``` js
function sendReq(){
const request = new Request("select @v1, @v2;", (err) =>{
console.log(err);
});
request.on('row', cols =>{
console.log(cols.map(x => x.value));
});
request.addParameter('v1', TYPES.TinyInt, 0.000000000000001);  // results in 1
request.addParameter('v2', TYPES.TinyInt, "0.00000000000001"); // results in 0
conn.execSql(request);
}
```
this PR fixes the commitlint issues in #823
> convert values using `Number` instead of `parseInt`

- src/connection.ts
- test/integration/connection-test.js
According to 
https://docs.microsoft.com/en-us/sql/t-sql/statements/set-arithabort-transact-sql, setting `ARITHABORT` to `OFF` can negatively impact query optimizations and lead to performance issues.
As `ARITHABORT` is set to `ON` by default in SQL Server Management Studio, having the same default in `tedious` ensures that matching query plans are generated and makes it easier to troubleshoot poorly performing queries.
BREAKING CHANGE: Changing the `ARITHABORT` setting changes how arithmetic, overflow, divide-by-zero, or domain errors are handled, and whether transactions that encounter these error conditions are rolled back or whether execution continues on.
References: https://github.com/tediousjs/tedious/pull/1025 
Fixes: https://github.com/tediousjs/tedious/issues/509
> Change `enableArithAbort` default to `true`

- .eslintrc
- package-lock.json
- package.json
- src/bulk-load.ts
- src/connection.ts
- src/data-type.ts
- src/data-types/bigint.ts
- src/data-types/binary.ts
- src/data-types/date.ts
- src/data-types/smallmoney.ts
- src/data-types/tvp.ts
- src/debug.ts
- src/login7-payload.ts
- src/message-io.ts
- src/message.ts
- src/metadata-parser.ts
- src/ntlm-payload.ts
- src/outgoing-message-stream.ts
- src/packet.ts
- src/prelogin-payload.ts
- src/request.ts
- src/sqlbatch-payload.ts
- src/token/colmetadata-token-parser.ts
- src/token/done-token-parser.ts
- src/token/infoerror-token-parser.ts
- src/token/nbcrow-token-parser.ts
- src/token/row-token-parser.ts
- src/token/sspi-token-parser.ts
- src/value-parser.ts
To support TypeScript syntax in `eslint`, we've used the `babel-eslint` parser module so far.
Unfortunately, that required disabling quite a few rules in our `eslintrc` config file:
https://github.com/tediousjs/tedious/blob/62ff4a10c4b1e1ef99b7f452cbaddef40c32f2cf/.eslintrc#L9
https://github.com/tediousjs/tedious/blob/62ff4a10c4b1e1ef99b7f452cbaddef40c32f2cf/.eslintrc#L27-L35
https://github.com/tediousjs/tedious/blob/62ff4a10c4b1e1ef99b7f452cbaddef40c32f2cf/.eslintrc#L47
These rules did not know about some of the specifics of TypeScript syntax or were simply not compatible with the AST that was returned by `babel-eslint`, and caused `eslint` to simply error out.
Luckily, there's an alternative and official way of making `eslint` better understand TypeScript syntax, called …
> Switch from `babel-eslint` to `@typescript-eslint`

- .eslintrc
- src/connection.ts
- src/rpcrequest-payload.ts
- src/sqlbatch-payload.ts
- src/transaction.ts
- test/integration/errors-test.js
Up until now, request payloads were generated by calling a `.getData` 
method on the request type's payload object, which would call the given 
callback with a `Buffer` containing the full request data.
As this requires the full request data to be fully build (and held in 
memory), actually writing the request to the network is delayed until 
the final `Buffer` was built.
This changeset switches us to use `Readable` stream objects instead. 
Internally, these are still building the full data buffer before, but 
this will be changed in the future.
This is part of the work described in https://github.com/tediousjs/tedious/issues/1038.
> refactor: use `Readable` streams to generate request payloads

- package-lock.json
- package.json
This updates `readable-stream` to `3.5.0`, which brings us the `Readable.from` static method that is a requirement for the work described over in https://github.com/tediousjs/tedious/issues/1038.
> chore: update to `readable-stream@3.5.0`

- benchmarks/common.js
- benchmarks/connection/open.js
- benchmarks/query/insert-varbinary.js
- benchmarks/query/select-many-rows.js
- benchmarks/query/select-nvarchar.js
- benchmarks/query/select-varbinary.js
- benchmarks/request/rpcrequest-payload-tvp.js
- benchmarks/request/rpcrequest-payload-varbinary.js
- benchmarks/token-parser/colmetadata-token.js
- benchmarks/token-parser/done-token.js
- benchmarks/token-parser/simple-tokens.js
This removes the need to run `npm run build` before running benchmarks, and ensures that the latest code changes are benchmarked.
> Change benchmarks to load the TypeScript code

- benchmarks/common.js
- benchmarks/query/insert-varbinary.js
- benchmarks/query/select-many-rows.js
- benchmarks/query/select-nvarchar.js
- benchmarks/query/select-varbinary.js
- benchmarks/request/rpcrequest-payload-tvp.js
- benchmarks/request/rpcrequest-payload-varbinary.js
This updates benchmarks with GC tracking. Because this tracking relies on the `perf_hooks` module, benchmarks can only be run on Node.js v8.5.0 and later. As we are planning to drop Node.js v6.x support soon anyway, that should be fine.
This also fixes an issue where we'd still load the compiled JavaScript files instead of the TypeScript source code when executing the benchmarks.
> Update benchmarks with GC tracking

- .travis.yml
- appveyor.yml
- src/connection.ts
- test/integration/connection-test.js
Defaulting `trustServerCertificate` to `true` is a potential security issue, so we should switch to it being set to false, and maybe even update our documentation to guide users to use the correct `cryptoCredentialsDetails` values to verify server certificates instead of relying on `trustServerCertificate`.
References: https://github.com/tediousjs/tedious/issues/983
> Deprecate default value for `trustServerCertificate ` being `true`

- src/connection.ts
- src/tedious.ts
- test/integration/connection-test.js
In https://github.com/tediousjs/tedious/pull/730, the ability to build a new `Connection` object without immediately opening the actual connection to the server was requested.
I think this requested behavior should actually be the **default**. This is also how `net.Socket` in NodeJS works - calling `new net.Socket` won't actually open a connection to the remove server, unless the `.connect` method is called on the returned socket object. The `net` module also provides a module level `.connect` convenience method that creates and returns a new `Socket` instance and calls `.connect` on it.
This pull request adds a similar method on the `tedious` module, that creates a new `Connection`, calls `.connect` on it and returns the created connection object.
Calling `new Connection` without …
> Deprecate automatically opening a connection when building a `Connection` instance

- src/connection.ts
- src/token/colmetadata-token-parser.ts
- src/token/done-token-parser.ts
- src/token/env-change-token-parser.ts
- src/token/feature-ext-ack-parser.ts
- src/token/fedauth-info-parser.ts
- src/token/infoerror-token-parser.ts
- src/token/loginack-token-parser.ts
- src/token/nbcrow-token-parser.ts
- src/token/order-token-parser.ts
- src/token/returnstatus-token-parser.ts
- src/token/returnvalue-token-parser.ts
- src/token/row-token-parser.ts
- src/token/sspi-token-parser.ts
- src/token/stream-parser.ts
- src/token/token-stream-parser.ts
- test/unit/token/row-token-parser-test.js
This removes the `colMetadata` parameter on the Parser classes and the individual token parser functions.
The rationale behind removing it from the Parser classes is that it was always set to `undefined` in the `tedious` codebase, except for in the tests, where we can also just set the property directly to whatever we want it to be.
The rationale behind removing it from the token parser function is that it was only used by the `ROW` and `NBCROW` token parser functions, and the column information can also be accessed simply via the property on the parser instance that is also passed to those functions.
> refactor: simplify `Parser` constructor

- test/integration/transactions-test.js
On SQLServer 2019, this test would sometimes fail, because the error message would change from just
```
String or binary data would be truncated.
```
to
```
String or binary data would be truncated in table 'tempdb.dbo.#temp_______________________________________________________________________________________________________________000000000002', column 'value'. Truncated value: 'asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfas'.
```
As we don't actually care about the exact error message, we can change the assertion to match just the beginning of the error message and thus make this test pass on both newer and older SQLServer versions.
> Fix running tests on SQLServer 2019

- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/test-connection.json
This adds configuration files for a `devcontainer` setup, as supported in VS Code.
This enables a relatively quick and painful way to set up a fully functional development environment for `tedious`, which works even in the browser via [GitHub Codespaces](https://github.com/features/codespaces/) or [Visual Studio Codespaces](https://visualstudio.microsoft.com/services/visual-studio-codespaces/).
The environment that will be spun up consists of one "JavaScript Development Container", and an additional container running  SQLServer 2019 for Linux. A `test-connection.json` file for running unit and integration tests will also be set up automatically.
> Add `devcontainer` configuration

- package-lock.json
- package.json
- test/integration/rpc-test.js
- test/mocha.opts
- tsconfig.json
These changes will allow us to write test cases using TypeScript, in addition to the existing tests written in plain JavaScript.
> Support writing test cases using TypeScript

- src/bulk-load.ts
- src/data-type.ts
- src/login7-payload.ts
- src/metadata-parser.ts
- src/ntlm-payload.ts
- src/prelogin-payload.ts
- src/request.ts
- src/token/colmetadata-token-parser.ts
- src/token/done-token-parser.ts
- src/token/infoerror-token-parser.ts
- src/token/nbcrow-token-parser.ts
- src/token/row-token-parser.ts
- src/token/sspi-token-parser.ts
This is a cleanup extracted from https://github.com/tediousjs/tedious/pull/995, and just switches `type` assignments with `interface` declarations.
There is not really much of a difference between those two. See https://medium.com/@martin_hotell/interface-vs-type-alias-in-typescript-2-7-2a8f1777af4c for a blog post highlighting the difference more closely.
The main intent for switching from one to the other is to just be a bit more consistent.
> refactor: prefer TypeScript's `interface` over `type`

- src/tedious.ts
This fixes the type signature of the `connect` helper that was added in https://github.com/tediousjs/tedious/pull/1069.
Note: this is marked as `refactor` because we don't yet publish type signatures and this has thus no impact on users.
> refactor: update `connect` helper type signature

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- .travis.yml
This adds CI jobs to run on GitHub Actions, with the intent of replacing our use of Travis CI.
A full CI run on GitHub Actions takes 7-8 minutes, where as a Travis CI run takes around 16 minutes, at least. It also seems to me that the azure builds are a bit more stable (but that remains to be seen).
One disadvantage of GitHub Actions compared to Travis CI is that if a single CI job fails on GitHub Actions, all jobs have to be re-run. But with the much quicker runtime compared to Travis CI, I don't think that'll be an issue. 🤷
> Set up GitHub Actions

- .github/workflows/nodejs.yml
This fixes the `Error: Expected TRAVIS_PULL_REQUEST_SLUG to be defined globally, it was not.` failure when GitHub Actions executes the commit message linter after a push to the `master` branch. (https://github.com/tediousjs/tedious/runs/773821309)
> ci: fix running`commitlint` on GitHub Actions

- .github/workflows/nodejs.yml
As Pull Requests that are opened from a forked repository don't have access to secrets that contain the Azure username and password, so we want to skip running that job.
This fixes a mistake I made that prevented the Azure job from being skipped.
> ci: fix condition for running tests against Azure

- .vscode/settings.json
This adds a settings file for VS Code that should match our linter settings a bit more closely.
> chore: add a VS Code settings file

- src/connector.ts
- src/instance-lookup.ts
- src/sender.ts
- test/unit/connector-test.js
- test/unit/instance-lookup-test.js
- test/unit/sender-test.js
This removes the stubbing of `dns.lookup` we had in place in some of our test cases.
This stubbing was error prone and lead to a whole bunch of flaky test failures on CI.
Instead of stubbing functions, this changes relevant code to allow passing in a custom `lookup` function, but falling back to `dns.lookup` if that function is `undefined`.
Closes: https://github.com/tediousjs/tedious/pull/988
> Stop stubbing `dns` module

- src/connection.ts
This fixes an issue where after a server redirect, we would continue to use the original servername when trying to establish a TLS connection. This issue is only visible when `trustServerCertificate` was explicitly set to `false`, as otherwise the hostname returned by the certificate was never verified.
Fixes: https://github.com/tediousjs/tedious/issues/1081
> fix: use proper servername for TLS after redirect

- .github/workflows/release.yml
I think this was broken when I moved our CI from Travis over to GitHub Actions.
> chore: try to fix npm release tagging

- src/connection.ts
- src/incoming-message-stream.ts
- src/message-io.ts
- test/integration/invalid-packet-stream-test.js
- test/unit/incoming-message-stream-test.js
When the server sends invalid packet header data, we will now correctly pass a `ConnectionError` to the `callback` given to `TranformStream._transform`.
Fixes: #1074
References: #1101
> fix: correctly handle invalid packet headers

- src/bulk-load.ts
- src/connection.ts
- test/integration/bulk-load-test.js
- test/unit/bulk-load-test.js
- test/unit/connection-config-validation.js
Validate function will report error is input data do not match the data type check. However, the current bulk logic does not expose this error. Added some logic to expose these errors. 
Related issue: #889
> feat: allow validating bulk load parameters

- benchmarks/common.js
- examples/bulkLoad-sample.js
- examples/minimal.js
- examples/parameters.js
- examples/simple-client.js
- examples/storedProcedureWithParameters.js
- src/connection.ts
- test/integration/binary-insert-test.js
- test/integration/bulk-load-test.js
- test/integration/connection-retry-test.js
- test/integration/connection-test.js
- test/integration/errors-test.js
- test/integration/parameterised-statements-test.js
- test/integration/pause-resume-test.js
- test/integration/prepare-execute-statements-test.js
- test/integration/rpc-test.js
- test/integration/socket-error-test.js
- test/integration/transactions-test.js
- test/integration/tvp-test.js
- test/performance/big-select.js
The callback passed to `Connection.prototype.connect` could in some error cases be called without an error argument.
This issue was introduced in https://github.com/tediousjs/tedious/pull/1102.
> `connect` callback could miss `err` argument

- package.json
This makes some of the `commitlint` checks a bit less strict. This should keep dependabot PRs like https://github.com/tediousjs/tedious/pull/1176 from failing.
> chore: relax `commitlint` configuration a bit

- src/connection.ts
The typing is defined for the internal interface, but not for the external interface.
Since newer node versions contains changes to the default TLS settings (e.g. minimum TLS version), more users would need to set the `cryptoCredentialDetails`.
Adding the typing would make that easier.
> chore: add typing to cryptoCredentialDetails

- package-lock.json
- package.json
This updates `codecov` to properly support GitHub Actions.
> chore: upgrade to `codecov@3.8.1`

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- src/connection.ts
- test/integration/connection-retry-test.js
- test/integration/connection-test.js
We use the `@azure/ms-rest-nodeauth` package to perform all Azure ActiveDirectory related authentication steps. That library builds on top of `node-adal` and provides a higher level API and authentication methods that `node-adal` does not provide (like MSI VM and Service authentication).
Because requesting an authentication token is pretty slow (it can take 500ms or much more), `node-adal` exposes a in-memory token caching mechanism. Each request can specify a token cache, or a global token cache will be used instead. Unfortunately, the high level API that `@azure/ms-rest-nodeauth` exposes and that we use, provides a new token cache for each authentication request. In theory, it allows passing in a custom token cache, but that logic is not working correctly (see …
> fix: improve Azure AD authentication performance

- src/connection.ts
This removes all functionality that is currently deprecated, and will cause a new major release. This will most likely be the last release before we drop any support for Node 6.x and 8.x.
> Remove deprecated functionality

- package-lock.json
- package.json
- src/connection.ts
- src/instance-lookup.ts
- src/sender.ts
- test/unit/instance-lookup-test.js
- test/unit/sender-test.js
This refactors the `Sender` helper class (used for instance lookup) to implement cancellation behavior on top of the `AbortController` (and `AbortSignal`) interfaces.
This also adds test cases that cover cancellation behavior and increases the overall test coverage.
This is mostly in preparation to convert this part of the code over to `async`/`await` and with the eventual goal of fixing issues like https://github.com/tediousjs/tedious/issues/782.
> refactor: use `AbortController` to implement cancellation

- src/connection.ts
- src/connector.ts
- src/instance-lookup.ts
- test/integration/instance-lookup-test.js
- test/unit/connector-test.js
- test/unit/instance-lookup-test.js
This adds `AbortSignal` support to the `Connector` and `InstanceLookup` classes.
None of this is really used so far, but it's laying the foundation to properly resolve the issue described in https://github.com/tediousjs/tedious/issues/782, and similar issues, where after the connection attempt times out, errors can still happen.
> Add `AbortSignal` support to `Connector` and `InstanceLookup`

- src/connection.ts
- test/integration/connection-test.js
This fixes the issue of dangling sockets after connection timeout, as described in https://github.com/tediousjs/tedious/issues/782.
This was caused by the simple fact that the `Connector` class did not allow aborting any in-flight connection attempts. So if the connection timeout was reached after `Connector.execute` was called, but before the connection attempt failed or succeeded, any in-flight sockets were not cleaned up correctly.
This could potentially lead to errors being emitted _after_ establishing the connection already failed. It also lead to Node.js processes not shutting down correctly until all the dangling sockets timed out, often many seconds later.
Fixes: https://github.com/tediousjs/tedious/issues/782
> Correctly abort connect operations on connect timeout

- examples/minimal.js
This PR fixes the `minimal` example, which is currently broken.
Running the example currently yields no output, as a `connect()` call is missing. Adding the missing call executes the query as expected after the connection is ready.
> fix: add connection.connect() to broken minimal example

- .flowconfig
We've switched from `flow` to `typescript` quite some while ago.
> Delete unused `flow` configuration file

- src/data-types/varbinary.ts
- src/data-types/varchar.ts
- test/unit/data-type.js
Refactors varchar and varbinary data-type to generate exact length specified by the user when generating `TYPE_INFO`
> Fix `varchar` and `varbinary` to generate exact length in `TYPE_INFO` header

- src/connection.ts
- src/message-io.ts
- test/unit/message-io-test.js
The TDS protocol is message based - the client sends a request message to the server, and the server sends a response message back. Messages are broken up into smaller packets, that are sent over the connection, but there is no interleaving of packets from different messages.
But the way that message handling in tedious is implemented is not making this obvious. Different states have separate `data` (for message contents) and `message` (for the end of a message) handlers. This generally works fine. If a message is received, data is processed via `data` events and then once the message is fully handled, the `message` event should handle cleanup tasks, like switching to a different state.
Unfortunately, that model easily gets messed up if we switch the connection before a message has been …
> refactor: improve message handling

- benchmarks/token-parser/colmetadata-token.js
- benchmarks/token-parser/done-token.js
- benchmarks/token-parser/simple-tokens.js
- src/connection.ts
- src/request.ts
- src/token/stream-parser.ts
- src/token/token-stream-parser.ts
- src/token/token.ts
- test/integration/pause-resume-test.js
- test/unit/token/token-stream-parser-test.js
This further cleans up some logic around message handling.
The biggest change here is that each message is handled by a new token parser object. This allows us to get rid of the "fake" `EndOfMessageToken`, and we can simply wait for the `end` event coming from the token parser. This opens up the possibility to use directly `.pipe` a message into the token parser directly, or convert the token parser to an async generator function that consumes a message. This will be explored in a follow up PR.
There's some additional changes around pause/resume and cancellation behavior, but those should not make much of a difference.
---
These changes have a small negative impact on performance, because each incoming message generates a new token parser object, and registers a bunch of event handlers. …
> Cleanups around message handling

- src/token/stream-parser.ts
- test/unit/token/colmetadata-token-parser-test.js
- test/unit/token/done-token-parser-test.js
- test/unit/token/env-change-token-parser-test.js
- test/unit/token/feature-ext-parser-test.js
- test/unit/token/fedauth-info-parser-test.js
- test/unit/token/infoerror-token-parser-test.js
- test/unit/token/loginack-token-parser-test.js
- test/unit/token/order-token-parser-test.js
- test/unit/token/row-token-parser-test.js
- test/unit/token/sspi-token-parser-test.js
- test/unit/token/token-stream-parser-test.js
This PR refactors current unit/token tests to call the updated stream-parser function properly. 
- There are currently 3 failing tests (all from row-stream-parser-test.js)
- For `token/stream-parser.ts`, I've added 
- An overall `try catch` for the whole `*parseTokens` function
- A `yield null` on line 101 (to keep the behavior consistent with master)
- An optional premade `Parser` object in the `*parseTokens` function to get row-token-parser tests working properly
> refactor: wip: updating token unit tests

- benchmarks/token-parser/colmetadata-token.js
- benchmarks/token-parser/done-token.js
- benchmarks/token-parser/simple-tokens.js
- src/connection.ts
- src/metadata-parser.ts
- src/token/env-change-token-parser.ts
- src/token/stream-parser.ts
- src/token/token-stream-parser.ts
- src/value-parser.ts
- test/integration/pause-resume-test.js
- test/unit/token/colmetadata-token-parser-test.js
- test/unit/token/done-token-parser-test.js
- test/unit/token/env-change-token-parser-test.js
- test/unit/token/feature-ext-parser-test.js
- test/unit/token/fedauth-info-parser-test.js
- test/unit/token/infoerror-token-parser-test.js
- test/unit/token/loginack-token-parser-test.js
- test/unit/token/order-token-parser-test.js
- test/unit/token/row-token-parser-test.js
- test/unit/token/sspi-token-parser-test.js
- test/unit/token/token-stream-parser-test.js
This pull request converts the token parsing code from a `Transform` stream into a async generator function that consumes a `AsyncIterable<Buffer>` and yields back parsed tokens.
All of the existing token parsing implementation is retained, this mostly just switches out how the parsing is "driven". This gives us the option to call other async code during the parsing (e.g. as is required for always encrypted to get encryption keys).
Right now, the async generator is wrapped in a `Readable.from` call, so we can keep most of the existing code as-is.
This depends on https://github.com/tediousjs/tedious/pull/1226 to be merged first.
---
This change has a negative impact on performance, mostly because we introduce some additional overhead by having a async generator and wrapping it back into a …
> Convert token parser to an async generator function

- test/integration/bulk-load-test.js
Just general cleanup for bulk load integration tests, better test naming, using arrow functions, cleaning up the syntax, fixing variable naming.
> Clean up bulk load integration tests a bit

- src/token/colmetadata-token-parser.ts
- src/token/nbcrow-token-parser.ts
- src/token/row-token-parser.ts
- src/token/stream-parser.ts
- test/integration/request/max-columns-test.ts
- test/unit/token/colmetadata-token-parser-test.js
- test/unit/token/nbcrow-token-parser-test.js
- test/unit/token/row-token-parser-test.js
This reworks the `COLMETADATA`, `ROW` and `NBCROW` token parsing logic to parse incoming data in a fashion that does not grow the call stack in relation to the incoming packet size.
Fixes: #839
Fixes: #1206
> Fix maximum call stack errors when parsing query results

- src/connection.ts
node-mssql tests have failed when I bumped from v11.0.5 -> v11.0.7 and one of those failures was because the error being emitted here wasn't being passed to the callback.
This fixes the problem
> fix: procedure validate errors not being caught

- .github/workflows/nodejs.yml
This tries to fix codecov reporting by switching to the official GitHub Action for codecov.
> ci: switch to codecov action

- appveyor.yml
Node.js 13.x is not maintained, so there's no point in us running tests against that version. 😅
> ci: drop Node.js 13.x builds from Appveyor

- .github/workflows/nodejs.yml
It looks like microsoft has stopped publishing MSSQL for linux containers under the `microsoft/mssql-server-linux` name on dockerhub.
Fortunately, fixing this is simple, as we can just switch over to `mcr.microsoft.com/mssql/server` instead. 👍
> ci: update mssql linux container to be pulled from MCR

- src/always-encrypted/get-parameter-encryption-metadata.ts
- src/connection.ts
- src/request.ts
- src/rpcrequest-payload.ts
This refactors how RPC request parameters are handled. There's two main changes here:
* https://github.com/tediousjs/tedious/commit/fc80fa6df79ee1aa0d820a8115965fb870d6bbc9 removes the dependence of `RPCRequestPayload` on `Request` instances, instead it now takes a stored procedure name or id, and the list of parameters explicitly.
* https://github.com/tediousjs/tedious/commit/f4e26f2f0c29de9578a16c033b16196e6207a601 removes a tiny bit of mutability from `Request` objects. Previously, when calling `Connection.execSql`, `Connection.prepare`, `Connection.unprepare` or `Connection.execute`, the passed `Request` object's parameters were modified in-place, and original parameters were copied over to an internal `originalParameters` property. Instead of doing that, we now build the final …
> Refactor RPC parameter handling

- src/connection.ts
Looks like the documentation was copied from the wrong method. 😅
> docs: fix `execBulkLoad` documentation

- src/connection.ts
This deprecates setting `validateBulkLoadParameters` to `false`.
This option was added to ease migration for code that relied on missing bulk load parameter validation. Skipping bulk load validation can lead to really weird bugs, so validating parameters should not be optional.
The `validateBulkLoadParameters` option will be removed in the next major release.
> Deprecate `validateBulkLoadParameters` connection option

- src/bulk-load.ts
- test/integration/bulk-load-test.js
This fixes an issue where bulk loads into tables with unusual names or column names (e.g. containing emoji or special characters like `"` or `[` and others) would fail, even though the names themselves would be seen as valid by SQL Server.
This changes the database statements generated by the bulk load code to escape these identifiers correctly.
> Support exotic table names in `BulkLoad`s

- package-lock.json
Fixes a tiny mismatch in our `package-lock.json` that would show up when running `npm install`.
> chore: update `package-lock.json`

- benchmarks/bulk-load/stream.js
- benchmarks/bulk-load/sync.js
This adds 2 benchmarks for evaluating the performance of the `BulkLoad` code, one using `BulkLoad.addRow` for "synchronous" bulk loads where all data is already available in memory, and another one using `BulkLoad.getRowStream` for "streaming" bulk loads where not all data is loaded into memory upfront.
> Add `BulkLoad` benchmarks

- src/bulk-load-payload.ts
- src/bulk-load.ts
- src/connection.ts
This refactors bulk load internals and prepares the code for future changes (see https://github.com/tediousjs/tedious/pull/1280).
This aligns the code internal code that handles sending `BulkLoad` and `Request` objects to the server, and makes them both follow the same structure.
Based on the benchmark code added in #1287, these refactorings also increase performance of the bulk loading code.
---
```
root ➜ /workspaces/tedious (master ✗) $ node benchmarks/bulk-load/stream.js 
bulk-load/stream.js size=10 n=10: 272.78394483173855 (minor: 0 - 0ms, major: 0 - 0ms, incremental: 0 - 0ms)
bulk-load/stream.js size=100 n=10: 105.15348060071281 (minor: 1 - 0.713903ms, major: 0 - 0ms, incremental: 0 - 0ms)
bulk-load/stream.js size=1000 n=10: 41.32809930037975 (minor: 3 - 2.5318110000000003ms, major: …
```
> Refactor bulk load internals

- src/bulk-load.ts
- test/integration/bulk-load-test.js
When doing a streaming bulk load, `tedious` only supported writing arrays to the stream returned by `bulkLoad.getRowStream`. This updates the stream to also handle objects correctly, in the same way the `bulkLoad.addRow` API already does.
> feat: allow using objects in addition to arrays for streaming bulk loads

- src/bulk-load.ts
- test/integration/bulk-load-test.js
This reverts the changes introduced in commit a67c0ad65abdb58e3aabc1c58b2b765ca2214175. This caused existing code that referenced tables using their fully qualified name to break unexpectedly.
Fixes: https://github.com/tediousjs/tedious/issues/1292
References: https://github.com/tediousjs/node-mssql/issues/1276
> revert: revert support for exotic table and column names in bulk loads

- package-lock.json
- package.json
- src/connection.ts
- src/request.ts
- test/integration/binary-insert-test.js
- test/integration/bulk-load-test.js
- test/integration/connection-test.js
- test/integration/errors-test.js
- test/integration/instance-lookup-test.js
- test/integration/invalid-packet-stream-test.js
- test/integration/parameterised-statements-test.js
- test/integration/pause-resume-test.js
- test/integration/prepare-execute-statements-test.js
- test/integration/rpc-test.js
- test/integration/socket-error-test.js
- test/integration/tvp-test.js
- tsconfig.json
This enables the `allowJs` option in the typescript configuration, which allows the use of the typescript compiler to type check `.js`.
Type checking will be opt-in initially, and can be enabled for individual files by adding a `// @ts-check` comment. Having all test files type checked will ensure that the types defined in the TypeScript code are "correct" and is a first step to including TypeScript definition files in our npm packages in the future.
> Allow type checking on JavaScript files

- src/connection.ts
This `unpipe`s the payload stream from the outgoing message when the current request is canceled, or an error happens in the payload stream.
This is in preparation for https://github.com/tediousjs/tedious/pull/1303, where not calling `unpipe` will cause `write after end` errors in newer Node.js versions (`16.x.x` and later).
> fix: unpipe payload streams on cancel or error

- src/bulk-load-payload.ts
This changes the `.destroy` call on the row transform stream when a bulk load is cancelled to only be called with an error if the request is in streaming mode.
This change is in preparation of dropping the dependency on the `readable-stream` module.
> fix: only destroy with error when in streaming mode

- package.json
- src/bulk-load.ts
- src/connection.ts
- src/incoming-message-stream.ts
- src/message-io.ts
- src/message.ts
- src/outgoing-message-stream.ts
- src/token/token-stream-parser.ts
The `readable-stream` module hasn't been updated for a long time, and it looks like it might not receive any updates in the future.
`readable-stream` was based on the `stream` core module as shipped with Node.js 10.x. As this is the oldest version of Node.js we support anyway, including `readable-stream` does not bring us anything. Newer Node.js versions ship with improved but fully backwards-compatible core streams, so we can just use them instead.
> feat: drop dependency on `readable-stream`

- benchmarks/bulk-load/iterable.js
- src/bulk-load.ts
- src/connection.ts
- test/integration/bulk-load-test.js
This adds a new `BulkLoad` API that greatly simplifies streaming data for bulk loading.
Instead of having to access a `BulkLoad`'s via the `.getRowStream` method, we can now simply pass in an `Iterable` (like a regular `Array` or a `Generator`) or an `AsyncIterable` (like a `ReadableStream` or an `AsyncGenerator`) to the `.execBulkLoad` method on a `Connection`.
Here's a very basic example that streams data from a regular `Array`:
```js
const bulkLoad = connection.newBulkLoad('employees', (err, rowCount) => {
// ...
});
bulkLoad.addColumn('first_name', TYPES.NVarchar, { nullable: false });
bulkLoad.addColumn('last_name', TYPES.NVarchar, { nullable: false });
bulkLoad.addColumn('date_of_birth', TYPES.Date, { nullable: false });
connection.execBulkLoad(bulkLoad, [
{ 'first_name': 'Steve', …
```
> New BulkLoad streaming API

- .github/workflows/nodejs.yml
This enables GitHub Actions workflows for more branches, namely `alpha`, `beta` and all branches that follow the `*.x` naming pattern. This will allow us to manage alpha, beta, and maintenance releases in a much more straightforward fashion.
> ci: enable GitHub Actions workflow for more branches

- src/connection.ts
- test/integration/connection-test.js
Co-authored-by: MichaelSun90 <v-mutsun@microsoft.com>
This is a fix for issue #873. We have fixed the problem for the option key textsize, and added some additional tests for this.
> fix: fix handling of `textsize` connection option

- .github/workflows/nodejs.yml
- appveyor.yml
- package.json
Security support for Node.js 10.x officially ended in April 2021. I think it's safe to drop support for it in `tedious` as well.
> feat: drop support for Node.js 10.x 

- src/bulk-load.ts
- src/connection.ts
- test/integration/bulk-load-test.js
- test/unit/bulk-load-test.js
- test/unit/connection-config-validation.js
BREAKING CHANGE: This removes the `validateBulkLoadParameters` connection option and always enables validation of bulk load values.
> feat: remove `validateBulkLoadParameters` connection option

- src/collation.ts
This adds support for reading data from `varchar`/`char`/`text` columns that would be read with the wrong encoding previously.
This is based on the collations supported in SQL Server 2019.
Closes: https://github.com/tediousjs/tedious/pull/1301
> feat: add missing collation codepage information

- src/bulk-load.ts
- src/data-types/image.ts
- src/data-types/ntext.ts
- src/data-types/text.ts
- test/integration/bulk-load-test.js
- test/integration/parameterised-statements-test.js
While working on collation support, I noticed that we don't correctly support `text`/`ntext`/`image` column types in bulk loads, and we actually don't even support `ntext` for regular parameters either.
This adds support for these data types in bulk loads (and as regular parameters in case of `ntext` as well).
> Support `text`/`ntext`/`image` in bulk loads

- src/always-encrypted/get-parameter-encryption-metadata.ts
- src/bulk-load.ts
- src/collation.ts
- src/connection.ts
- src/data-type.ts
- src/data-types/char.ts
- src/data-types/nchar.ts
- src/data-types/ntext.ts
- src/data-types/nvarchar.ts
- src/data-types/text.ts
- src/data-types/varchar.ts
- src/metadata-parser.ts
- src/request.ts
- src/rpcrequest-payload.ts
- src/token/env-change-token-parser.ts
- src/token/token-stream-parser.ts
- src/token/token.ts
- src/value-parser.ts
- test/integration/collation-test.ts
- test/unit/bulk-load-test.js
- test/unit/collation-test.ts
- test/unit/data-type.js
- test/unit/token/colmetadata-token-parser-test.js
- test/unit/validations.js
This refactors the collation parsing logic and fixes some issues around parsing the different collation flags.
It also adds tracking of collation information on the connection, and also ensures we write back the collation for `varchar` / `nvarchar` / `char` / `nchar` / `text` / `ntext` values.
> Improve collation handling

- src/connection.ts
- src/login7-payload.ts
- src/token/feature-ext-ack-parser.ts
- src/token/token.ts
- test/unit/login7-payload-test.js
- test/unit/token/feature-ext-parser-test.js
Before, we did not send the UTF-8 option during login, nor did we parse the corresponding FeatureExtAck from the server.
Now, we do.
(Though TBH, I'm not clear on how this actually changes the server behavior; it seemed perfectly happy to send UTF-8 encoded data on down to versions of the library that did not express UTF-8 support. So we could maybe drop the last commit, which remembers the status, since we probably don't need to actually check it ever.)
> feat: log in with UTF-8 option [#1143]

- src/connection.ts
The `msiEndpoint` and `msiSecret` authentication options will no longer be supported once we switch over to `@azure/identity` for Azure authentication.
See https://github.com/tediousjs/tedious/pull/1328
> feat: deprecate azure authentication options that will be removed

- .github/workflows/nodejs.yml
In preparation for the `@azure/identity` migration.
> ci: specify azure tenant id

- benchmarks/query/call-tvp.js
Add a benchmark to better understand performance of requests with large TVP parameters. See https://github.com/tediousjs/tedious/issues/1338
> chore: add a `tvp` benchmark

- src/data-types/tvp.ts
- test/integration/collation-test.ts
- test/integration/tvp-test.js
This fixes a `varchar` and `char` encoding when used inside TVP parameters by enabling parameter validation.
> Fix `varchar` and `char` encoding in TVPs

- src/request.ts
- test/unit/request-test.js
These `options` object to the `Request.addOutputParameter` and `Request.addParameter` methods is owned by whatever is calling these methods, and any modification to these objects by `tedious` is rather unexpected. By creating a copy of the object, we can avoid modifying it.
> fix: do not modify objects passed to `Request.addOutputParameter` or `Request.addParameter`

- src/connection.ts
- test/integration/prepare-execute-statements-test.js
This was causing unexpected `returnValue` events.
Fixes: #1344
> fix: do not specify `handle` as an output parameter when calling `sp_execute`/`sp_unprepare`

- src/bulk-load.ts
- test/integration/collation-test.ts
When calling `.addRow` on a `BulkLoad`, column values would get validated twice, once in the `.addRow` call and a second time in the `RowTransform` stream. This could lead to incorrect values being written (e.g. for `varchar` values).
> fix: prevent bulkload values from being validated twice

- package-lock.json
- package.json
- src/bulk-load.ts
- src/connection.ts
`BulkLoad.addRow` and `BulkLoad.getRowStream` will be removed in the next major version of `tedious`.
Additionally, the `sspichallenge` event on `Connection` is deprecated and will be removed.
> Emit deprecation warnings for deprecated functionality

- api-connection.html
- bulk-load.html
This removes the documentation for `BulkLoad.addRow` and `BulkLoad.getRowStream`. Both these methods are deprecated and will be removed soon.
> docs: remove documentation for deprecated bulk load API

- api-connection.html
After a customer conversation, I noticed some of the Azure AD authentication options were missing from the API doc.
> docs: Add Azure AD auth options to the connection API docs

- src/connection.ts
In preparation for fixing #1361. Emits a warning to deprecate in the future. Default value will be changed back to false.
> feat: deprecate default value for trustServerCertificate

- examples/bulk-load.js
- examples/minimal.js
- examples/prepared.js
- examples/table-valued-parameters.js
- examples/transaction.js
Changed the example files to use the callback function in `.connect()` instead of using the event handler.
Removed `addRow` from `bulk-load.js`
Executes SQL after it has been prepared in `prepared.js`
> docs: update examples to deprecate old functionality

- api-connection.html
> docs: rename `domain` to `tenantId` in azure ad password type, pr #1386

- src/connection.ts
- src/token/handler.ts
add azure-active-directory-default as an authentication option
This leverages `DefaultAzureCredential` from `@azure/identity` which allows for seamless development to deployment by using local credentials developer identity but will also use msi in a cloud service or vm.
For those not familiar `DefaultAzureCredential` derives from  `ChainedTokenCredential` and will attempt different credentials after each failed currently the chain is 
```js
export const defaultCredentials: DefaultCredentialConstructor[] = [
EnvironmentCredential,
DefaultManagedIdentityCredential,
VisualStudioCodeCredential,
AzureCliCredential,
AzurePowerShellCredential
]
```
Closes #1284
> feat: add azure-active-directory-default as an authentication option

- api-connection.html
- bulk-load.html
Adds documentation for new BulkLoad API.
- Adds `options` to `connection.newBulkLoad()` in the Connection page
- Adds `rows` to `connection.execBulkLoad()` in the Connection page with basic examples
> docs: update bulkload docs

- src/connection.ts
This refactors some of the state handling in the `Connection` class to make use of `async`/`await`.
The goal here is to gradually move us to a more readable, maintainable and overall more robust connection handling logic.
For now, this only focuses on the following states:
* `SENT_PRELOGIN`
* `SENT_TLSSSLNEGOTIATION`
* `SENT_LOGIN7_WITH_STANDARD_LOGIN`
* `SENT_LOGIN7_WITH_NTLM`
* `LOGGED_IN_SENDING_INITIAL_SQL`
The other states will be tackled in followup pull requests.
> refactor: refactor `Connection` state implementation

- .github/workflows/lint-pull-request-title.yml
We want to lower the burden of contributions by switching away from the current workflow that requires each commit to be tagged according to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) rules.
Instead, we want to switch to a "squash and merge" based workflow, where a pull requests's title becomes the source of the final commit that will be merged. This will allow contributors not to have to care about their commit messages, and maintainers can just edit the pull request's title before merging a pull request to make it fit our contribution rules.
> ci: lint pull request titles

- .eslintrc
- src/always-encrypted/keystore-provider-azure-key-vault.ts
Contrary to what one might believe, `await`ing on `Promise` value before returning from an `async` function actually has better performance than returning a `Promise` value directly in v8. This is due to optimizations that the engine can perform when using the `await` keyword.
On top of that, v8's async stack trace functionality only works correctly when `await` is used consistently here.
> chore: always require `await`ing on promises before return

- src/connection.ts
Continuation of #1437. 
This refactors some of the state handling in the Connection class to make use of async/await.
The goal here is to gradually move us to a more readable, maintainable and overall more robust connection handling logic.
This PR changes the following states:
- `SENT_LOGIN7_WITH_FEDAUTH`
- `SENT_ATTENTION`
- `SENT_CLIENT_REQUEST`
> refactor: further `Connection` state implementation refactor

- package.json
Tedious code uses `stream.Readable.from`
https://nodejs.org/api/stream.html#streamreadablefromiterable-options
which was added in v12.3.0, v10.17.0.
> chore: clarify mininum compatible node version

- src/connection.ts
- test/integration/child-processes/ntlm-connect-node17.js
- test/integration/connection-test.js
- test/unit/child-processes/ntlm-payload-node17.js
- test/unit/ntlm-payload-test.js
Emits an error explaining that the user needs to enable `--openssl-legacy-provider`. Also adds tests to test the flag's functionality. 
Document changes: #1399 (already merged)
CI Config testing node 17: #1396
> feat: fail ntlm auth gracefully when md4 hashing is not available

- src/connection.ts
- src/message-io.ts
- test/unit/message-io-test.ts
Currently, TLS negotiation happens via inside a "special" connection state called `SENT_TLSSSLNEGOTIATION`, and the logic for performing the handshake procedure is spread across two classes (`Connection` and `MessageIO`) and multiple methods.
This pull requests moves all of the tls negotation logic into `MessageIO#startTls`. It also improves TLS error handling during negotiation and adds multiple unit tests to ensure that the logic is covered and working correctly.
> refactor: refactor tls negotiation code

- src/connection.ts
- src/connector.ts
- src/errors/abort-error.ts
- src/errors/timeout-error.ts
- src/instance-lookup.ts
- src/sender.ts
- src/utils/with-timeout.ts
- test/integration/instance-lookup-test.js
- test/unit/connector-test.js
- test/unit/instance-lookup-test.js
- test/unit/sender-test.js
This is an attempt to start moving some of the `tedious` internals over to use `async`/`await`.
> refactor: convert `InstanceLookup` and `Sender` to use `async`/`await` and support `AbortSignal`

- src/connection.ts
- src/message-io.ts
- test/integration/connection-test.js
- test/unit/message-io-test.ts
Modifies tests to pass on Node 18.6.0+
> fix: set maximum supported TLS version to 1.2

- src/data-types/bigint.ts
- src/ntlm-payload.ts
- src/token/done-token-parser.ts
- src/token/stream-parser.ts
- src/tracking-buffer/writable-tracking-buffer.ts
- test/unit/tracking-buffer/writable-tracking-buffer-test.js
We used JSBI as a polyfill for BigInt on older Node.js versions. All versions of Node.js that we currently support also support BigInt out-of-the box, so we can drop the dependency on that. Resolving issue #1468
> feat: replace `JSBI` with native `BigInt`

- src/connection.ts
I noticed that the config validation for the `connectTimeout` option is duplicated.
> refactor: remove duplicate config validation

- src/connection.ts
- test/integration/connection-test.js
This fixes #1261 (at least under my test conditions).
I'm not sure if this is the best way to handle errors at connection time, but it seems that the time is not being cleared correctly if/when a connection errors before being established.
> fix: clear connection timeout on connection error

- .github/workflows/codeql-analysis.yml
- .github/workflows/nodejs.yml
- .github/workflows/release.yml
This PR bumps GitHub Actions to their latest major versions, which now use Node 16 internally instead of Node 12 (EOL as of end of April 2022, no longer receives security updates):
- Releases for `actions/cache` can be [found here](https://github.com/actions/cache/releases)
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
-   Changelog for `github/codeql-action` actions can be [found here](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
> ci: update github actions

- src/parser/index.ts
- test/unit/parser/parser-test.ts
Adds the following base parsers:
- `int8`
- `int16le`
- `int32le`
Adds unit tests for:
- `int8`
- `uint8`
- `int16le`
- `int32le`
- `uint32le`
> refactor: parser combinator additions

- src/parser/index.ts
- src/token/loginack-token-parser.ts
- src/token/returnstatus-token-parser.ts
- test/unit/connection-retry-test.js
- test/unit/parser/parser-test.ts
- test/unit/rerouting-test.js
This PR includes the following base parsers and unit tests:
- `int32be`
- `bvarchar`
- `uint32be`
- `biguint64le`
Includes following token parsers:
- `returnstatusparser`
- `loginack`
> refactor: additional parsers

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- appveyor.yml
- package-lock.json
- package.json
BREAKING CHANGE: Node.js 14.x is no longer supported by `tedious`.
> chore: drop node 14 support, add node 19 support

- .github/workflows/nodejs.yml
Tests against Azure have been incredibly flaky recently. Make them non-required for creating a new release (I already made them non-required for merging a pull request).
> ci: don't require azure tests to pass for release

- .github/workflows/nodejs.yml
Error handling in our CI suite is not optimal. We often end up with CI stuck when we run into a test failure, because resources are not cleaned up correctly (e.g. network sockets don't get closed).
By default, builds time out on GitHub Actions after 360 minutes, while our builds usually take around 10 minutes. So if the tests get stuck, we spent up to 6 hours just doing nothing and hogging up resources. Instead, let's fail the build after 20 minutes.
> ci: timeout builds after 20 minutes

- .github/workflows/nodejs.yml
New CUs were released for Windows SQL Server 2019 and 2022, and the old URLs are no longer valid.
> ci: update windows sql server 2019 and 2022 update urls

- examples/custom-connector.js
- src/connection.ts
- test/unit/custom-connector.js
This changeset adds a new `connector` config option that may be used to define a custom socket factory method. Providing a much more flexible control of the socket connection creation.
Defining a custom `connector` config value allows **Tedious** to support a larger variety of environments/setups such as proxy servers using secure socket connections that are used by cloud providers such as GCP.
Linked below, the `pg` driver for PostgreSQL and the `mysql2` driver for MySQL are prior art example of this pattern. Also linked below is the Cloud SQL Node.js Connector, which demonstrates how third-party libraries can leverage the custom socket factory method.
**Refs:** https://github.com/sidorares/node-mysql2/blob/ba15fe25703665e516ab0a23af8d828d1473b8c3/lib/connection.js#L63-L65
**Refs:** …
> feat: add connector factory method

- .github/workflows/nodejs.yml
Pulls latest update from same URL so removes need to manually change URL with every SQL Server cumulative update
> ci: update windows ci download links

- src/connection.ts
Issue: https://github.com/tediousjs/tedious/issues/1485
Queries that return a response before finishing have ability to run longer than the `requestTimeout`.
When a response is received the timeout for the request is cancelled. This is because it can't be known what the client will do with the response.
> docs: Add Comment About A Request Lasting Longer Than Its Timeout

- test/integration/parameterised-statements-test.js
> test: fix TVP test not working on Azure SQL

- frequently-encountered-problems.html
Explains how `tedious-connection-pool` and `node-mssql` are not maintained by us
> docs: third party library faq update

- test/integration/connection-test.js
Our encrypt tests are not running due to SQL version detection that we added. This PR fix that. 
When the test actually running, we found out that TDS7_1 does not compatible with SQL server 2022, so we will skip corresponding tests.
> test: fix TDS 8.0 test cases not being executed correctly

- test/helpers/debug-options-from-env.ts
- test/integration/binary-insert-test.js
- test/integration/bulk-load-test.js
- test/integration/collation-test.ts
- test/integration/connection-test.js
- test/integration/datatypes-in-results-test.ts
- test/integration/errors-test.js
- test/integration/invalid-packet-stream-test.js
- test/integration/parameterised-statements-test.js
- test/integration/pause-resume-test.js
- test/integration/prepare-execute-statements-test.js
- test/integration/rpc-test.js
- test/integration/socket-error-test.js
- test/integration/transactions-test.js
- test/integration/tvp-test.js
This allows enabling debug output during test runs by setting the `TEDIOUS_DEBUG` variable. The value for the variable is a string containing a value like `packet`, `data`, `payload`, `token`, or any combination of these values separated by `,`.
> test: allow easier test debugging via `TEDIOUS_DEBUG` env variable

- api-connection.html
David suggested we update the doc to: 
A string value set to 'strict' enables the TDS 8.0 protocol. Otherwise, encrypt can be set to a boolean value which determines whether or not the connection will be encrypted under the TDS 7.x protocol. (default: true ).
> doc: update the encrypt via a suggestion

- src/always-encrypted/aead-aes-256-cbc-hmac-algorithm.ts
- src/always-encrypted/aead-aes-256-cbc-hmac-encryption-key.ts
- src/always-encrypted/cek-entry.ts
- src/always-encrypted/keystore-provider-azure-key-vault.ts
- src/always-encrypted/symmetric-key.ts
- src/bulk-load-payload.ts
- src/bulk-load.ts
- src/collation.ts
- src/connection.ts
- src/debug.ts
- src/errors.ts
- src/errors/abort-error.ts
- src/errors/timeout-error.ts
- src/incoming-message-stream.ts
- src/login7-payload.ts
- src/message-io.ts
- src/message.ts
- src/ntlm-payload.ts
- src/outgoing-message-stream.ts
- src/packet.ts
- src/prelogin-payload.ts
- src/request.ts
- src/rpcrequest-payload.ts
- src/sqlbatch-payload.ts
- src/token/handler.ts
- src/token/stream-parser.ts
- src/token/token-stream-parser.ts
- src/token/token.ts
- src/tracking-buffer/writable-tracking-buffer.ts
- src/transaction.ts
add declare for class level properties regard to #1579
> feat: improve performance on Node.js 16 by disabling class property definitions

- src/connection.ts
- src/data-types/date.ts
- src/message-io.ts
- src/request.ts
- src/value-parser.ts
Hello, I noticed a handful of typos throughout some of the comments and JSDoc's, so I decided to submit a quick PR to fix them.
Thanks!
> docs: fix various typos

- package-lock.json
- package.json
- src/connector.ts
- src/sender.ts
- test/unit/connector-test.js
- test/unit/instance-lookup-test.js
The slash at the end is necessary to use the userland module. The module built-in to node is deprecated.
> fix: use userland module for `punycode`

- package-lock.json
- package.json
- src/connector.ts
- src/sender.ts
- test/unit/connector-test.js
- test/unit/instance-lookup-test.js
Seems that native node:url supports the same functionality that tedious required. Replace punnyCode side function with url.domainToASCII.
> refactor: replace `punycode` with `node:url`

- src/data-types/date.ts
- src/data-types/datetime.ts
- src/data-types/datetime2.ts
- src/data-types/datetimeoffset.ts
- src/data-types/smalldatetime.ts
- test/unit/data-type.js
> fix: date range check

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- appveyor.yml
- package-lock.json
- package.json
BREAKING CHANGE: Node.js 16.x and 19.x are no longer supported by `tedious`.
> chore!: drop node 16 and 19 support

- src/tedious.ts
Thanks for adding first-party typings! I've noticed that ConnectionConfiguration wasn't exported, while we are using that for sequelize here; https://github.com/sequelize/sequelize/blob/main/packages/core/src/dialects/mssql/connection-manager.ts (@types/tedious calls it ConnectionConfig but the object is basically the same as ConnectionConfiguration)
I went ahead and just exported the type here, but I'm open to hear if you have other suggestions on what type to use.
> feat(types): export `ConnectionConfiguration` type

- src/connection.ts
- src/tedious.ts
These types are used by `@types/mssql`. If this isn't desirable then we could propose a change to the type definitions in DefinitelyTyped.
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/24a1115cea9315062833ded8a59de6ac9f627f2f/types/mssql/index.d.ts#L209
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/24a1115cea9315062833ded8a59de6ac9f627f2f/types/mssql/index.d.ts#L179
```console
node_modules/@types/mssql/index.d.ts(179,44): error TS2694: Namespace '"node_modules/tedious/lib/tedious"' has no exported member 'ConnectionOptions'.
node_modules/@types/mssql/index.d.ts(209,26): error TS2694: Namespace '"node_modules/tedious/lib/tedious"' has no exported member 'ConnectionAuthentication'.
```
> feat(types): Export `ConnectionAuthentication` and `ConnectionOptions`

- src/data-types/bigint.ts
- test/unit/validations-test.js
This PR is for fixing issue #1610 
Now the validate function will throw an error if a invalid value is passed into BigInt type :
"The number <value> cannot be converted to a BigInt because it is not an integer"
> fix: fix `bigint` validation

- .github/workflows/nodejs.yml
Bump the version of `codecov/codecov-action` used in GitHub Actions.
> ci: bump `codecov/codecov-action`

- .github/workflows/nodejs.yml
See here for updated link: 
https://github.com/MicrosoftDocs/SupportArticles-docs/blob/main/support/sql/releases/sqlserver-2019/cumulativeupdate27.md
under "How to obtain or download the latest cumulative update package for Windows (recommended)"
> ci: update links to windows SQL server cumulative updates

- src/debug.ts
- src/token/token-stream-parser.ts
I don't know exactly when this was broken, but it looks like we haven't been getting any debug output from the `options.debug.token` option.
This also fixes one use of `any` in the `token` method in `Debug` by changing the type of the `token` parameter to `Token`.
> fix: fix `options.debug.token` option not causing any debug output

- src/connection.ts
This was extracted from https://github.com/tediousjs/tedious/pull/1634 and makes some of the `ConnectionOptions` properties accept `undefined` values.
It also fixes the type for the `textSize` option to be a `number` instead of a `string`.
> fix: fix type information on some `ConnectionOptions` properties

- src/data-types/smalldatetime.ts
- test/unit/data-type.js
> fix: correct SmallDateTime upper bound range

- src/data-types/bigint.ts
- test/unit/int-data-type.js
Passing big integer values as bigint parameters caused a RangeError with the following message:
`RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -(2n ** 63n) and < 2n ** 63n. Received 9_223_372_036_854_775_808n`.
The patch removes this unneeded conversion and instead convert other types to BigInt.
> fix: don't convert BigInt type to Number before writing to buffer to prevent RangeError

- .github/workflows/nodejs.yml
- package-lock.json
- package.json
- src/connection.ts
- test/config.token-credential.ts
This pull request contains the changes from https://github.com/tediousjs/tedious/pull/1624, plus the CI changes to run integration tests using the new token credential authentication type.
> feat: Token Credential Support

- .github/workflows/codeql-analysis.yml
- .github/workflows/nodejs.yml
- .github/workflows/release.yml
This upgrades various GitHub Actions to their latest versions, and removes usage of the deprecated `set-output` command.
> ci: GitHub Actions cleanup

- src/bulk-load.ts
- test/integration/bulk-load-test.js
I got an `uncaughtException`, caused by trying to write a very large (negative) number using BulkLoad to a decimal column. Seems similar to https://github.com/tediousjs/tedious/issues/421. The stack trace I got:
```
RangeError: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 3_.40_282_346_638_528_86e_+42
File "node:internal/errors", line 496, in __node_internal_captureLargerStackTrace
File "node:internal/errors", line 405, in new NodeError
File "node:internal/buffer", line 74, in checkInt
File "node:internal/buffer", line 694, in writeU_Int32LE
File "node:internal/buffer", line 707, in Buffer.writeUInt32LE
File "/app/node_modules/tedious/src/data-types/decimal.ts", line 77, in Object.generateParameterData
File "<anonymous>", line unknown, in …
```
> fix: don't throw in _transform of BulkLoad

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
1. The setup-node action automatically stores caches for NPM and uses the same logic as the current action implementation, so there's no need to duplicate it in the action definition.
2. Remove redundant NPM upgrade step - v6.x of Node is no longer tested/supported.
3. Linting step does not need complete repository history.
4. Use [setup-sqlserver](https://github.com/tediousjs/setup-sqlserver) action to install SQL Server
> ci: improve github actions

- src/connection.ts
- src/errors.ts
- src/request.ts
- test/integration/connection-test.js
This pull request updates `ConnectionError` and `RequestError` with support for a new `options` argumenton their constructor. This parameter mirrors the `options` of `Error` base class and allows setting a `cause`.
I updated all the locations where `ConnectionError` or `RequestError` are constructed to set the `cause` if available.
> feat: set error cause if available

- package.json
increase the project mocha timeout to 10 seconds to prevent `dns.lookup` timeout
> ci: increase mocha timeout

- src/connection.ts
This cleans up the rerouting and retry implementations.
Instead of adding state specific logic to the overall `close` socket handler, we now just remove the `close` and `end` socket handlers and call `socket.destroy` before we perform rerouting or retry logic.
This moves the logic closer together and helps making it simpler to understand what's going on for both of these features.
> refactor: cleanup rerouting and retry implementation

- src/connection.ts
This moves the logic that lived in the connection state machine into proper methods.
> refactor: move connecting state logic into proper methods

- src/connection.ts
- test/integration/connection-test.js
- test/unit/connection-failure-test.js
* Instead of calling `this.socketError`, throw errors and have them handled centrally in `initialiseConnection`.
* Use `async`/`await` wherever possible.
> refactor: simplify connection establishment

- README.md
I noticed a handful of the badges at the top of the README have broken links and/or are unused. I thought I'd go ahead and submit a PR to remove them.
before:
after:
Thanks!
> docs: remove broken badge links
