tediousjs/tedious

index.html

Add a paragraph to the github pages link to detail which version to use for Azure SQL DB.
For issue #258

Azure SQL DB version information

---

package.json

Release Proposal: 1.11.2

---

package.json

This includes the following changes:
* Release automation using travis: Pushing a new tag to the github repository will automatically try to release a new version of `tedious` on `npm`. #254 
* Run more CI builds on travis, on the fast container infrastructure. #283 
* Make AppVeyor builds a bit more stable. #252 
* Do not let invalid dates pass the data validation check. #276

Release 1.11.3

---

package.json

The major change in this release is a revamped, generator based stream parsing code.
The new stream parsing significantly reduces the memory used by tedious and increases performance. These improvements are especially noticable when fetching results with large columns (like `varbinary(max)` or `nvarchar(max)`). A simple benchmark for transferring a 50MB `varbinary` data shows that `tedious` now uses only 60MB (instead of more than 320MB) of memory and parsing is 10000% faster. For smaller data sizes, the improvements are not as profound but still noticeable.
All `tedious` dependencies were also bumped to their latest versions to ensure we include all their latest fixes.
* #288 Upgrade dependencies to their latest versions
* #285 Generator based stream parser

Release v1.12.0

---

package.json
src/token/nbcrow-token-parser.coffee

This fixes the issue mentioned in #291.

Release 1.12.1

---

.travis.yml
appveyor.yml

Builds on branches that have an open Pull Requests will still trigger.

Only run builds on the master branch.

---

src/message-io.coffee
src/token/stream-parser.coffee
test/unit/token/colmetadata-token-parser-test.coffee
test/unit/token/done-token-parser-test.coffee
test/unit/token/env-change-token-parser-test.coffee
test/unit/token/infoerror-token-parser-test.coffee
test/unit/token/loginack-token-parser-test.coffee
test/unit/token/order-token-parser-test.coffee
test/unit/token/row-token-parser-test.coffee
test/unit/token/sspi-token-parser-test.coffee

This fixes token and received packet debug output, which got lost in the code changes for #285.

Fix debug output

---

src/connection.coffee

In addition to #309.
I can push another beta package, just need some other pair of eyes looking over this.
//cc @gleeds @bretcope @tysjiang @SyRenity @spanditcaa PTAL

Send correct servername in Login7 after rerouting

---

src/connection.coffee

This is basically a forward port of the changes included in 1.11.5, bringing those to the 1.12 release line.

Fix handling of rerouting events in 1.12 release line

---

src/token/stream-parser.js

This makes the stream parsing code a lot less memory intensive, as the stack will be no longer deeply nested when parsing incoming data. It's not providing an obvious benefit in all cases, but it lays some groundwork that I'll be using for further changes.
This is the last thing I want to get in before I cut a `1.13.0` release.
Benchmarks:
Before:
```
Many result rows x 3.95 ops/sec ±1.91% (24 runs sampled)
Memory: 68.53125 MiB
inserting nvarchar(max) with 5242880 chars x 20.32 ops/sec ±2.63% (54 runs sampled)
Memory: 117.2109375 MiB
inserting nvarchar(max) with 4 chars x 534 ops/sec ±1.36% (82 runs sampled)
Memory: 22.62890625 MiB
inserting varbinary(4) with 4 bytes x 535 ops/sec ±1.37% (79 runs sampled)
Memory: 22.265625 MiB
inserting varbinary(max) with 50 MiB x 4.47 ops/sec ±1.78% (26 …
```

Make the stream parser iterative instead of recursive.

---

.travis.yml
appveyor.yml
package.json
src/rpcrequest-payload.js
test/integration/parameterised-statements-test.coffee

This includes #336 which fixes #335.

Release 1.13.1

---

package.json

This release adds support for Variant data type and fixes problems with some SQL collations.
#350 Add Variant data type support
#376 Fix parsing of SQL collations
#361 Align to code style used in Node 4+

Release 1.14.0

---

.eslintrc
package.json
src/token/token-stream-parser.js
src/tracking-buffer/writable-tracking-buffer.js
src/transaction.js
src/value-parser.js
test/setup.js

This upgrades some of the dependencies used by tedious to their latest version.

Upgrade Dependencies

---

README.md

Should fix the broken readme on NPM
https://www.npmjs.com/package/tedious

Fix README on npm

---

src/connection.js
test/unit/tedious-test.js

We should verify that the config we were given is not falsy and that we at least have a server name to connect to.

Make config handling a bit stricter.

---

src/connector.js
test/unit/connector-test.js

Added a test case for connecting to/from IPv6 address.
Throw a IPv6 address into the mix of IP addresses in tests.

Make DNS lookup for both IPv4 and IPv6 instead of just IPv4.

---

src/connection.js
test/integration/connection-test.coffee

This addresses https://github.com/tediousjs/tedious/issues/482

Invoke Request callback with error if connection closed prematurely.

---

test/integration/datatypes-in-results-test.coffee
test/integration/parameterised-statements-test.coffee

This adds tests for the PR https://github.com/tediousjs/tedious/pull/517.

Added tests for DateTime precision.

---

_layouts/default.html

Since pekim.github.com no longer exists.

Update site search to look at tediousjs.github.io

---

src/connection.js
src/transient-error-lookup.js
test/integration/connection-retry-test.js
test/unit/connection-config-validation.js
test/unit/transient-error-lookup-test.js

@arthurschreiber @chdh This adds retries for transient failures that all Microsoft drivers do to improve reliability. This could address some of the connection failures issues that have been reported over time.

Transient failure retries

---

src/value-parser.js
test/integration/datatypes-in-results-test.js

Supports sql_varaint for variable length data types

---

package.json
src/connection.js
src/login7-payload.js
src/token/sspi-token-parser.js
test/integration/connection-test.js
test/unit/login7-payload-test.js
test/unit/token/sspi-token-parser-test.js

- This is currently implemented for Windows only.
- No username/password needed when connecting as domain user.
- Leverages current implementation of NTLM authentication that requires
username/password.
- Adds a dependency on https://www.npmjs.com/package/sspi-client package
for implementation of SSPI protocol.
- sspi-client has native code which means the module will be built on
client machines at Tedious installation time.
Address issue - https://github.com/tediousjs/tedious/issues/415
This is a squashed version of the work done under
https://github.com/tediousjs/tedious/pull/486

Implementation and tests for Windows Integrated Authentication.

---

api-connection.html
api-request.html

See #379.  Attempting to make the documentation a bit more clear.
I may do a quick run through all the documentation later and make sure that all <code> elements also link to their respective items in the documentation.

Add clarifying details around done events.

---

api-request.html

This is the API documentation for #518.

API documentation for pause/resume

---

README.md

Adding a button for the survey

---

package.json
src/data-type.js
test/unit/data-type.js

Fixed by first executing the multiplication and then the addition.

Fix for issue #599 (Rounding error on nanosecondDelta)

---

.gitignore
api-connection.html
api-request.html
bulk-load.html
getting-started.html

Adding documentation for Integrated auth, some missing config options and requestCompleted event.
#570 #464 #485

Updates to documentation

---

api-request.html

This provides documentation for issue #632 as resolved by pull #633

API documentation for request error event

---

bulk-load.html

Adding docs to `gh-page` till we migrate to documentation.js

Documentation for BulkLoad options.

---

README.md

Our surveybuilder account is going away. Need to update the link to point to a new survey.

Updating the survey link.

---

test/integration/connection-test.js

This adds a test case for #682.

test: Add a test to verify no errors are thrown after connect timeout.

---

.travis.yml
package.json

Version 6 installs deprecated packages, updated to fix warning messages on install

chore: update semantic-release version

---

pull_request_template.md

Adding a pull request template that lists the per-checks to run before submitting a PR.

docs: pre-checks to run before submitting pull prequest

---

README.md

Proposing a few minor changes to the README for anyone who wants to try out tedious.
- Spell out the prereq/dependency for installing tedious
- Add code samples keyword to documentation line (helps Google searches)
- Welcome community contributions

docs: suggested README.md changes

---

src/connection.js

fix: update timeout error with instance name

---

test/integration/pause-resume-test.js

This should fix the flaky CI failures happening on AppVeyor and Travis every now and then. 👍

test: increase timeouts to work around flaky tests

---

.travis.yml
test/integration/connection-test.js
test/integration/pause-resume-test.js

Updating tests to pass in Azure CI.
Test run that show error is in https://travis-ci.org/v-suhame/tedious/jobs/388396034.

ci: fix failure in Azure CI testing

---

LICENSE
README.md

chore: update copyright year

---

licence.html

chore: update the copyright year

---

benchmarks/common.js
examples/simple-client.js
test/integration/binary-insert-test.js
test/integration/bulk-load-test.js
test/integration/connection-retry-test.js
test/integration/connection-test.js
test/integration/datatypes-in-results-test.js
test/integration/errors-test.js
test/integration/instance-lookup-test.js
test/integration/parameterised-statements-test.js
test/integration/pause-resume-test.js
test/integration/prepare-execute-statements-test.js
test/integration/rpc-test.js
test/integration/socket-error-test.js
test/integration/transactions-test.js
test/integration/tvp-test.js
test/performance/big-select.js

home env variable is USERPROFILE in windows, process.env.HOME might be `undefined`. the issue manifested in vm or docker windows image.

fix: home directory lookup issue on windows

---

src/bulk-load.js
src/connection.js
src/request.js

Implements Request.setTimeout() and BulkLoad.setTimeout(), which can be used to override the timeout specified when the connection was created.

feat: add `Request.setTimeout()` and `BulkLoad.setTimeout()`

---

README.md

I'm not using Gitter, and I don't think any other contributor really does either.

docs: replace Gitter with Slack

---

src/all-headers.js
src/collation.js
src/data-type.js
src/debug.js
src/guid-parser.js
src/message-io.js
src/ntlm-payload.js
src/packet.js
src/prelogin-payload.js
src/request.js
src/sqlbatch-payload.js

This adds a whole bunch of flow annotations to files that were missing them before.
The types might not be 100% accurate, but it's definitely better than having no types at all. 😅

refactor: add more flow type information

---

package.json
test/setup.js

Update to Babel 7

---

src/connection.js

This fixes a few issues that came up after I released the configuration rework as part of v4.0.0. 🤦‍♂️

Configuration fixes

---

test/integration/connection-retry-test.js
test/integration/connection-test.js

Without this, connection-rety-test will not be done.

fix connection-retry-test to support new authentication option

---

src/connection.js

Another set of fixes regarding NTLM authentication after the configuration rework in v4.0. 🤦‍♂️

fix connecting via NTLM authentication

---

README.md

Update survey image link

---

api-connection.html
getting-started.html

docs: update gh-pages to reflect new authentication

---

src/connection.js

Fixes: #841 
Fixes: #835 
thanks @shani117 for your insights 😄

fix: add rerouting event to fedauth login

---

src/token/stream-parser.js

fix: correct callback of token stream parser transform

---

bulk-load.html

This is the API documentation for #547.

API documentation for streaming BulkLoad

---

src/connection.js

Transitions between states should, as much as possible, only happen in state code, in an ordered fashion. Transitioning to the retry state while not all data in a message has been processed can lead to very unexpected behaviour, like events being dispatched to the wrong state.

refactor: do not transition to retry state outside of state code

---

.travis.yml
appveyor.yml
examples/bulkLoad-sample.js
examples/minimal.js
examples/parameters.js
examples/storedProcedureWithParameters.js
src/connection.js
src/data-type.js
test/integration/connection-test.js
test/unit/data-type.js

This removes all functionality that was deprecated in older versions of `tedious`.

Remove all deprecated functionality

---

getting-started.html

missing bracket in getting started docs

missing bracket

---

package-lock.json
package.json

I hope this fixes the syntax related build failures we've seen on Travis. 😕

chore: upgrade all `babel` related packages to the latest version

---

api-connection.html

- Re-ordered the config options to alphabetical order
- add missing config options

docs: updated the tedious connection config options

---

_layouts/default.html
frequently-encountered-problems.html

Add faq feq

---

src/connector.ts

This converts another file containing internal functionality to TypeScript.

Convert more pure JS files to TypeScript

---

src/connection.ts
test/integration/errors-test.js

refactor: cancelling before buffer

---

README.md

Chore: Update year, Fix: typo on "License"

---

src/connection.ts
src/data-types/varbinary.ts
src/data-types/varchar.ts
src/rpcrequest-payload.ts

This contains a few small improvements to the payload generation code that should slightly improve performance.

Small improvements to payload generation

---

.travis.yml

This updates the Azure database configuration we use when running CI tests on Travis.

chore: update Azure configuration for travis ci

---

.github/workflows/nodejs.yml

I somehow missed this step when migrating from Travis to GitHub Actions. 🙈

ci: perform pre-releases via GitHub Actions

---

src/data-types/uniqueidentifier.ts
test/unit/data-type.js

Fixes: https://github.com/tediousjs/tedious/issues/1085
Closes: https://github.com/tediousjs/tedious/pull/1086
---
@dhensby Can you take a look? 🙇‍♂️

fix: improve `UniqueIdentifier` data type validation

---

.gitignore
package-lock.json
package.json
src/bulk-load.ts
src/connection.ts
src/data-type.ts
src/metadata-parser.ts
src/request.ts
src/tedious.ts
src/token/colmetadata-token-parser.ts
tsconfig.json

This PR includes the changes for insert necessary function, event, and interface declarations to the project.  The TypeDoc will able to use the declarations and the type of information from typescript to generate web-based documentation. 
API's documented include
- Request
- BulkLoad
- Connection

Connection type doc

---

.github/workflows/release.yml

I'm not sure why, but it looks like the `.npmrc` file created by the `setup-node` action is not working quite right. Just creating it manually will hopefully fix this. 🤞

Manually create `.npmrc` file for GitHub Actions

---

src/connection.ts
test/integration/connection-test.js

Based on #1131 (Thanks @aklietz ❤️) with added tests.
Closes #1131.

Add `options.workstationId`

---

src/connection.ts

docs(enableArithAbort): default value is true

---

.github/workflows/nodejs.yml

ci: update ci

---

package-lock.json
package.json
src/connection.ts
tsconfig.json

Fix for #1146 
Refactors `.loginWithAppServiceMSI()` function config to include `clientId` for user-assigned MSI Auth

refactor: update @azure/ms-rest-nodeauth

---

.github/workflows/nodejs.yml

[Reference](https://github.com/actions/toolkit/issues/641)

chore: update .github/workflow environment var

---

src/connection.ts

Fix for https://github.com/tediousjs/tedious/issues/1171

fix: add domain option for AAD username & pass

---

package-lock.json
package.json

This should fix `azure-active-directory-password` in CI.

chore: upgrade to `@azure/ms-rest-nodeauth@3.0.6`

---

README.md

Updates README to reflect 2021

update readme year to 2021

---

src/connection.ts
test/integration/bulk-load-test.js

Fix `BulkLoad.setTimeout` to actually cancel the request

---

src/connection.ts
test/integration/prepare-execute-statements-test.js

We were not correctly cleaning up `cancel` event handlers when a request was not canceled. This was not an issue for single use requests, but when a request was prepared and reused many times, `cancel` event handlers were set up over and over again. This would cause a memory leak, and would actually break request cancellation.
This fixes the memory leak by making sure the `cancel` event handlers are cleaned up.
Fixes: #1201

Prevent memory leaks via event handlers

---

package-lock.json
package.json
src/always-encrypted/aead-aes-256-cbc-hmac-algorithm.ts
src/always-encrypted/aead-aes-256-cbc-hmac-encryption-key.ts
src/always-encrypted/cek-entry.ts
src/always-encrypted/get-parameter-encryption-metadata.ts
src/always-encrypted/key-crypto.ts
src/always-encrypted/keystore-provider-azure-key-vault.ts
src/always-encrypted/symmetric-key-cache.ts
src/always-encrypted/symmetric-key.ts
src/always-encrypted/types.ts
src/always-encrypted/utils.ts
src/connection.ts
src/data-type.ts
src/metadata-parser.ts
src/request.ts

This adds always encrypted methods that aren't used anywhere in the driver yet but will be in future AE related PR's

chore: add always-encrypted methods folder

---

src/bulk-load.ts

This fixes a long standing issues where `BulkLoad`s handled values of the given input rows differently than regular `Request`s handled their parameters.
A given `DataType`s `.validate` method serves two purposes:
* input validation
* input normalization
Validation is performed by checking whether the given value can be used for the given data type - throwing an error if it doesn't - and normalization is done by either returning the value as given or converting it to a more suitable representation. For example the `Date` data type normalizes values the different supported input types - `string`s and `Date` instances - to actual `Date` objects.
This normalization step was skipped on `BulkLoad`s, which could cause them throw unexpected exceptions, taking the whole Node.js process down in the …

fix: use normalized values for bulk loads

---

src/bulk-load.ts
test/integration/bulk-load-test.js

This adds a new `order` option to `Connection.prototype.newBulkLoad` that allows specifying the order of bulk loaded data.
This can increase the performance of the bulk load if the data is ordered in the same way as the target table of the bulk load.
Closes: https://github.com/tediousjs/tedious/issues/1197
Closes: https://github.com/tediousjs/tedious/pull/1198

feat: add `order` option to `BulkLoad`

---

src/connection.ts
src/prelogin-payload.ts
test/unit/connection-retry-test.js
test/unit/prelogin-payload-test.js
test/unit/rerouting-test.js
tsconfig.json

This adds the correct driver version sent in the PRELOGIN packet.

Sent the `tedious` version in the `PRELOGIN` payload

---

package-lock.json
package.json

This fixes https://github.com/tediousjs/tedious/issues/1297.

fix: upgrade to `@azure/ms-rest-nodeauth@3.0.10`

---

codeql-analysis.yml

This will replace the LGTM build.

ci: enable GitHub Code Scanning alerts

---

package-lock.json
package.json
src/connection.ts

See https://github.com/tediousjs/tedious/pull/1328 for more information. This PR is just here to ensure CI for Azure authentication is executed and passes.
Closes https://github.com/tediousjs/tedious/pull/1328.

Migrate to azure identity

---

package-lock.json
package.json
src/always-encrypted/keystore-provider-azure-key-vault.ts
src/bulk-load.ts
src/connection.ts
src/connector.ts
src/data-type.ts
src/message.ts
src/request.ts
src/token/colmetadata-token-parser.ts
src/token/stream-parser.ts
tsconfig.json

Enables [the `exactOptionalPropertyTypes` setting](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes).

Enable `exactOptionalPropertyTypes` TypeScript config option

---

_layouts/default.html
api-connection.html
frequently-encountered-problems.html
style/reset.css

Added the missing details for the ADD authentication types along with some simple scripts for the retrieve azure token.

docs: add details to the documentation for AAD auth types

---

package-lock.json
package.json

chore(deps): bump @azure/identity from 1.5.2 to 2.0.1

---

src/connection.ts

Renames `config.authenticaiton.options.domain` to `config.authenticaiton.options.tenantId`
when using the azure-active-directory-password authentication type.
domain can still currently be used but will emit a deprecation warning message if used.
Documentation changes: #1389

feat: rename `domain` to `tenantId` when using azure ad password

---

api-connection.html
frequently-encountered-problems.html

Document changes on explaining how to use NTLM with node 17

docs: update connection and faq with nltm and node 17 info

---

api-connection.html
frequently-encountered-problems.html

Also updates connection.options.cryptoCredentialsDetails.

docs: add faq for encryption options

---

api-connection.html

Adds Azure Active Directory Default authentication method

docs: add azure-ad-default

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

Added 3 issue templates:
1. Bug report
2. Feature request
3. Question

docs: add issue templates

---

frequently-encountered-problems.html

Adds FAQ section explaining how Tedious handles Unicode conversions

docs: add faq section for unicode conversions

---

src/connection.ts
test/integration/child-processes/ntlm-connect-node17.js
test/integration/connection-test.js

Fixes issue #1445 and modifies NTLM test suite to test a request using the NTLM connection.

fix: fix ntlm connection state bug

---

test/unit/message-io-test.ts

TDS 7.x only supports TLS versions up to TLS v1.2. TLS v1.3 is not supported.
This updates the recently added unit tests for the `startTls` method of the `MessageIO` class to reflect this. TLS v1.2 has different handshake behaviour (2 round trips usually), so the tests needed to be updated accordingly.

test: update `MessageIO` TLS related tests to use TLS v1.2

---

.github/workflows/nodejs.yml
.github/workflows/release.yml
appveyor.yml
package.json
src/connection.ts

Collection of various breaking changes.

Release breaking changes on `beta` branch

---

package-lock.json

The format of `package-lock.json` changed with newer versions of `npm`.

chore: update `package-lock.json`

---

src/token/fedauth-info-parser.ts

Not sure if this is the optimal approach to refactor this parser

refactor: refactor `fedauth-info-parser`

---

getting-started.html

Added a closing statement to make the example more production ready.

Close connection in the docs

---

.devcontainer/docker-compose.yml

This updates the devcontainer configuration to work with newer, non root based container images. It also updates the container image to use sql server 2022.

chore: update devcontainer settings

---

.github/workflows/nodejs.yml
test/integration/errors-test.js

ci: split azure jobs

---

.devcontainer/docker-compose.yml

chore: fix devcontainer setup

---

.github/workflows/nodejs.yml
package-lock.json
package.json

Since the PR will be squash and merged, so no need to check all the commit message with lint.

chore: remove commit lint messages check

---

api-connection.html

Update the doc page for encrypt setting according to TDS 8.0 changes

doc: update the encrypt setting for TDS8.0

---

package-lock.json
package.json

bump Azure identity lib version to 4.2.1 #1633

fix: update azure identity version

---

.github/workflows/nodejs.yml
package-lock.json
package.json

Upgrade to the latest typescript version.

chore: upgrade dependencies

---

.github/workflows/nodejs.yml
.github/workflows/release.yml
package.json

fix: update package configuration to publish provenance data
